/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.Alert;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * A(n) Attribution object
 */
@ApiModel(description = "A(n) Attribution object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class Attribution {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("event_id")
  private Integer eventId = null;

  @SerializedName("event_name")
  private String eventName = null;

  @SerializedName("event_time")
  private DateTime eventTime = null;

  @SerializedName("raw_event")
  private Object rawEvent = null;

  @SerializedName("user")
  private String user = null;

  @SerializedName("ip_address")
  private String ipAddress = null;

  @SerializedName("scope_name")
  private String scopeName = null;

  @SerializedName("alert")
  private Alert alert = null;

  @SerializedName("alert_id")
  private Integer alertId = null;

  public Attribution id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Attribution eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * GUID to uniquely identify each event
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "GUID to uniquely identify each event")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public Attribution eventName(String eventName) {
    this.eventName = eventName;
    return this;
  }

   /**
   * The requested action, which is one of the actions listed in the API Reference for the service
   * @return eventName
  **/
  @ApiModelProperty(example = "null", value = "The requested action, which is one of the actions listed in the API Reference for the service")
  public String getEventName() {
    return eventName;
  }

  public void setEventName(String eventName) {
    this.eventName = eventName;
  }

  public Attribution eventTime(DateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * ISO 8601 timestamp when the event occurred
   * @return eventTime
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the event occurred")
  public DateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(DateTime eventTime) {
    this.eventTime = eventTime;
  }

  public Attribution rawEvent(Object rawEvent) {
    this.rawEvent = rawEvent;
    return this;
  }

   /**
   * The event as it is sent in
   * @return rawEvent
  **/
  @ApiModelProperty(example = "null", value = "The event as it is sent in")
  public Object getRawEvent() {
    return rawEvent;
  }

  public void setRawEvent(Object rawEvent) {
    this.rawEvent = rawEvent;
  }

  public Attribution user(String user) {
    this.user = user;
    return this;
  }

   /**
   * The user associated with the event
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "The user associated with the event")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public Attribution ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * The apparent IP address that the request was made from for the given event
   * @return ipAddress
  **/
  @ApiModelProperty(example = "null", value = "The apparent IP address that the request was made from for the given event")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public Attribution scopeName(String scopeName) {
    this.scopeName = scopeName;
    return this;
  }

   /**
   * The agent through which the request was made, such as the AWS Management Console or an AWS SDK
   * @return scopeName
  **/
  @ApiModelProperty(example = "null", value = "The agent through which the request was made, such as the AWS Management Console or an AWS SDK")
  public String getScopeName() {
    return scopeName;
  }

  public void setScopeName(String scopeName) {
    this.scopeName = scopeName;
  }

  public Attribution alert(Alert alert) {
    this.alert = alert;
    return this;
  }

   /**
   * Associated Alert
   * @return alert
  **/
  @ApiModelProperty(example = "null", value = "Associated Alert")
  public Alert getAlert() {
    return alert;
  }

  public void setAlert(Alert alert) {
    this.alert = alert;
  }

  public Attribution alertId(Integer alertId) {
    this.alertId = alertId;
    return this;
  }

   /**
   * Associated Alert ID
   * @return alertId
  **/
  @ApiModelProperty(example = "null", value = "Associated Alert ID")
  public Integer getAlertId() {
    return alertId;
  }

  public void setAlertId(Integer alertId) {
    this.alertId = alertId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attribution attribution = (Attribution) o;
    return Objects.equals(this.id, attribution.id) &&
        Objects.equals(this.eventId, attribution.eventId) &&
        Objects.equals(this.eventName, attribution.eventName) &&
        Objects.equals(this.eventTime, attribution.eventTime) &&
        Objects.equals(this.rawEvent, attribution.rawEvent) &&
        Objects.equals(this.user, attribution.user) &&
        Objects.equals(this.ipAddress, attribution.ipAddress) &&
        Objects.equals(this.scopeName, attribution.scopeName) &&
        Objects.equals(this.alert, attribution.alert) &&
        Objects.equals(this.alertId, attribution.alertId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, eventId, eventName, eventTime, rawEvent, user, ipAddress, scopeName, alert, alertId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attribution {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    rawEvent: ").append(toIndentedString(rawEvent)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    scopeName: ").append(toIndentedString(scopeName)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    alertId: ").append(toIndentedString(alertId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

