/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.Organization;
import io.evident.models.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * A(n) AuditLog object
 */
@ApiModel(description = "A(n) AuditLog object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class AuditLog {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("item_type")
  private String itemType = null;

  @SerializedName("item_id")
  private Integer itemId = null;

  @SerializedName("action")
  private String action = null;

  @SerializedName("successful")
  private Boolean successful = null;

  @SerializedName("access_denied")
  private Boolean accessDenied = null;

  @SerializedName("user_ip")
  private String userIp = null;

  @SerializedName("user_email")
  private String userEmail = null;

  @SerializedName("platform")
  private String platform = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("organization_id")
  private Integer organizationId = null;

  @SerializedName("user")
  private User user = null;

  @SerializedName("user_id")
  private Integer userId = null;

  public AuditLog id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AuditLog itemType(String itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Item that was changed
   * @return itemType
  **/
  @ApiModelProperty(example = "null", value = "Item that was changed")
  public String getItemType() {
    return itemType;
  }

  public void setItemType(String itemType) {
    this.itemType = itemType;
  }

  public AuditLog itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * ID of the item that was changed
   * @return itemId
  **/
  @ApiModelProperty(example = "null", value = "ID of the item that was changed")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public AuditLog action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Action attempted on the item
   * @return action
  **/
  @ApiModelProperty(example = "null", value = "Action attempted on the item")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public AuditLog successful(Boolean successful) {
    this.successful = successful;
    return this;
  }

   /**
   * Shows if the action was successful
   * @return successful
  **/
  @ApiModelProperty(example = "null", value = "Shows if the action was successful")
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  public AuditLog accessDenied(Boolean accessDenied) {
    this.accessDenied = accessDenied;
    return this;
  }

   /**
   * Shows if access was denied
   * @return accessDenied
  **/
  @ApiModelProperty(example = "null", value = "Shows if access was denied")
  public Boolean getAccessDenied() {
    return accessDenied;
  }

  public void setAccessDenied(Boolean accessDenied) {
    this.accessDenied = accessDenied;
  }

  public AuditLog userIp(String userIp) {
    this.userIp = userIp;
    return this;
  }

   /**
   * The IP of the user attempting the action
   * @return userIp
  **/
  @ApiModelProperty(example = "null", value = "The IP of the user attempting the action")
  public String getUserIp() {
    return userIp;
  }

  public void setUserIp(String userIp) {
    this.userIp = userIp;
  }

  public AuditLog userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * The email of the user attempting the action
   * @return userEmail
  **/
  @ApiModelProperty(example = "null", value = "The email of the user attempting the action")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public AuditLog platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * The platform the user attempted the action from
   * @return platform
  **/
  @ApiModelProperty(example = "null", value = "The platform the user attempted the action from")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public AuditLog createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public AuditLog updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public AuditLog organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Associated Organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public AuditLog organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Associated Organization ID
   * @return organizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public AuditLog user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Associated User
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "Associated User")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public AuditLog userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Associated User ID
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "Associated User ID")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLog auditLog = (AuditLog) o;
    return Objects.equals(this.id, auditLog.id) &&
        Objects.equals(this.itemType, auditLog.itemType) &&
        Objects.equals(this.itemId, auditLog.itemId) &&
        Objects.equals(this.action, auditLog.action) &&
        Objects.equals(this.successful, auditLog.successful) &&
        Objects.equals(this.accessDenied, auditLog.accessDenied) &&
        Objects.equals(this.userIp, auditLog.userIp) &&
        Objects.equals(this.userEmail, auditLog.userEmail) &&
        Objects.equals(this.platform, auditLog.platform) &&
        Objects.equals(this.createdAt, auditLog.createdAt) &&
        Objects.equals(this.updatedAt, auditLog.updatedAt) &&
        Objects.equals(this.organization, auditLog.organization) &&
        Objects.equals(this.organizationId, auditLog.organizationId) &&
        Objects.equals(this.user, auditLog.user) &&
        Objects.equals(this.userId, auditLog.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, itemType, itemId, action, successful, accessDenied, userIp, userEmail, platform, createdAt, updatedAt, organization, organizationId, user, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLog {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    accessDenied: ").append(toIndentedString(accessDenied)).append("\n");
    sb.append("    userIp: ").append(toIndentedString(userIp)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

