/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.ExternalAccount;
import io.evident.models.Organization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) AzureGroup object
 */
@ApiModel(description = "A(n) AzureGroup object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class AzureGroup {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("organization_id")
  private Integer organizationId = null;

  @SerializedName("external_accounts")
  private List<ExternalAccount> externalAccounts = new ArrayList<ExternalAccount>();

  @SerializedName("external_account_ids")
  private List<Integer> externalAccountIds = new ArrayList<Integer>();

  public AzureGroup id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AzureGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AzureGroup createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public AzureGroup updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public AzureGroup url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Logging URL for this Azure Group.  It is only returned when first created.
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "Logging URL for this Azure Group.  It is only returned when first created.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public AzureGroup organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Associated Organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public AzureGroup organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Associated Organization ID
   * @return organizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public AzureGroup externalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
    return this;
  }

  public AzureGroup addExternalAccountsItem(ExternalAccount externalAccountsItem) {
    this.externalAccounts.add(externalAccountsItem);
    return this;
  }

   /**
   * Associated External Accounts
   * @return externalAccounts
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts")
  public List<ExternalAccount> getExternalAccounts() {
    return externalAccounts;
  }

  public void setExternalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
  }

  public AzureGroup externalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
    return this;
  }

  public AzureGroup addExternalAccountIdsItem(Integer externalAccountIdsItem) {
    this.externalAccountIds.add(externalAccountIdsItem);
    return this;
  }

   /**
   * Associated External Accounts IDs
   * @return externalAccountIds
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts IDs")
  public List<Integer> getExternalAccountIds() {
    return externalAccountIds;
  }

  public void setExternalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AzureGroup azureGroup = (AzureGroup) o;
    return Objects.equals(this.id, azureGroup.id) &&
        Objects.equals(this.name, azureGroup.name) &&
        Objects.equals(this.createdAt, azureGroup.createdAt) &&
        Objects.equals(this.updatedAt, azureGroup.updatedAt) &&
        Objects.equals(this.url, azureGroup.url) &&
        Objects.equals(this.organization, azureGroup.organization) &&
        Objects.equals(this.organizationId, azureGroup.organizationId) &&
        Objects.equals(this.externalAccounts, azureGroup.externalAccounts) &&
        Objects.equals(this.externalAccountIds, azureGroup.externalAccountIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, createdAt, updatedAt, url, organization, organizationId, externalAccounts, externalAccountIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AzureGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    externalAccounts: ").append(toIndentedString(externalAccounts)).append("\n");
    sb.append("    externalAccountIds: ").append(toIndentedString(externalAccountIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

