/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.CustomComplianceDomain;
import io.evident.models.CustomComplianceStandard;
import io.evident.models.CustomSignature;
import io.evident.models.Signature;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) CustomComplianceControl object
 */
@ApiModel(description = "A(n) CustomComplianceControl object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class CustomComplianceControl {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("position")
  private Integer position = null;

  @SerializedName("custom_compliance_standard")
  private CustomComplianceStandard customComplianceStandard = null;

  @SerializedName("custom_compliance_standard_id")
  private Integer customComplianceStandardId = null;

  @SerializedName("custom_compliance_domain")
  private CustomComplianceDomain customComplianceDomain = null;

  @SerializedName("custom_compliance_domain_id")
  private Integer customComplianceDomainId = null;

  @SerializedName("signatures")
  private List<Signature> signatures = new ArrayList<Signature>();

  @SerializedName("signature_ids")
  private List<Integer> signatureIds = new ArrayList<Integer>();

  @SerializedName("custom_signatures")
  private List<CustomSignature> customSignatures = new ArrayList<CustomSignature>();

  @SerializedName("custom_signature_ids")
  private List<Integer> customSignatureIds = new ArrayList<Integer>();

  public CustomComplianceControl id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CustomComplianceControl name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomComplianceControl identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * The identifier of this custom control
   * @return identifier
  **/
  @ApiModelProperty(example = "null", value = "The identifier of this custom control")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public CustomComplianceControl description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description for this custom control
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "The description for this custom control")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomComplianceControl createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public CustomComplianceControl updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public CustomComplianceControl position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * The position of this custom control within the custom domain
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "The position of this custom control within the custom domain")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public CustomComplianceControl customComplianceStandard(CustomComplianceStandard customComplianceStandard) {
    this.customComplianceStandard = customComplianceStandard;
    return this;
  }

   /**
   * Associated Custom Compliance Standard
   * @return customComplianceStandard
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Standard")
  public CustomComplianceStandard getCustomComplianceStandard() {
    return customComplianceStandard;
  }

  public void setCustomComplianceStandard(CustomComplianceStandard customComplianceStandard) {
    this.customComplianceStandard = customComplianceStandard;
  }

  public CustomComplianceControl customComplianceStandardId(Integer customComplianceStandardId) {
    this.customComplianceStandardId = customComplianceStandardId;
    return this;
  }

   /**
   * Associated Custom Compliance Standard ID
   * @return customComplianceStandardId
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Standard ID")
  public Integer getCustomComplianceStandardId() {
    return customComplianceStandardId;
  }

  public void setCustomComplianceStandardId(Integer customComplianceStandardId) {
    this.customComplianceStandardId = customComplianceStandardId;
  }

  public CustomComplianceControl customComplianceDomain(CustomComplianceDomain customComplianceDomain) {
    this.customComplianceDomain = customComplianceDomain;
    return this;
  }

   /**
   * Associated Custom Compliance Domain
   * @return customComplianceDomain
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Domain")
  public CustomComplianceDomain getCustomComplianceDomain() {
    return customComplianceDomain;
  }

  public void setCustomComplianceDomain(CustomComplianceDomain customComplianceDomain) {
    this.customComplianceDomain = customComplianceDomain;
  }

  public CustomComplianceControl customComplianceDomainId(Integer customComplianceDomainId) {
    this.customComplianceDomainId = customComplianceDomainId;
    return this;
  }

   /**
   * Associated Custom Compliance Domain ID
   * @return customComplianceDomainId
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Domain ID")
  public Integer getCustomComplianceDomainId() {
    return customComplianceDomainId;
  }

  public void setCustomComplianceDomainId(Integer customComplianceDomainId) {
    this.customComplianceDomainId = customComplianceDomainId;
  }

  public CustomComplianceControl signatures(List<Signature> signatures) {
    this.signatures = signatures;
    return this;
  }

  public CustomComplianceControl addSignaturesItem(Signature signaturesItem) {
    this.signatures.add(signaturesItem);
    return this;
  }

   /**
   * Associated Signatures
   * @return signatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Signatures")
  public List<Signature> getSignatures() {
    return signatures;
  }

  public void setSignatures(List<Signature> signatures) {
    this.signatures = signatures;
  }

  public CustomComplianceControl signatureIds(List<Integer> signatureIds) {
    this.signatureIds = signatureIds;
    return this;
  }

  public CustomComplianceControl addSignatureIdsItem(Integer signatureIdsItem) {
    this.signatureIds.add(signatureIdsItem);
    return this;
  }

   /**
   * Associated Signatures IDs
   * @return signatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Signatures IDs")
  public List<Integer> getSignatureIds() {
    return signatureIds;
  }

  public void setSignatureIds(List<Integer> signatureIds) {
    this.signatureIds = signatureIds;
  }

  public CustomComplianceControl customSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
    return this;
  }

  public CustomComplianceControl addCustomSignaturesItem(CustomSignature customSignaturesItem) {
    this.customSignatures.add(customSignaturesItem);
    return this;
  }

   /**
   * Associated Custom Signatures
   * @return customSignatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures")
  public List<CustomSignature> getCustomSignatures() {
    return customSignatures;
  }

  public void setCustomSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
  }

  public CustomComplianceControl customSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
    return this;
  }

  public CustomComplianceControl addCustomSignatureIdsItem(Integer customSignatureIdsItem) {
    this.customSignatureIds.add(customSignatureIdsItem);
    return this;
  }

   /**
   * Associated Custom Signatures IDs
   * @return customSignatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures IDs")
  public List<Integer> getCustomSignatureIds() {
    return customSignatureIds;
  }

  public void setCustomSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomComplianceControl customComplianceControl = (CustomComplianceControl) o;
    return Objects.equals(this.id, customComplianceControl.id) &&
        Objects.equals(this.name, customComplianceControl.name) &&
        Objects.equals(this.identifier, customComplianceControl.identifier) &&
        Objects.equals(this.description, customComplianceControl.description) &&
        Objects.equals(this.createdAt, customComplianceControl.createdAt) &&
        Objects.equals(this.updatedAt, customComplianceControl.updatedAt) &&
        Objects.equals(this.position, customComplianceControl.position) &&
        Objects.equals(this.customComplianceStandard, customComplianceControl.customComplianceStandard) &&
        Objects.equals(this.customComplianceStandardId, customComplianceControl.customComplianceStandardId) &&
        Objects.equals(this.customComplianceDomain, customComplianceControl.customComplianceDomain) &&
        Objects.equals(this.customComplianceDomainId, customComplianceControl.customComplianceDomainId) &&
        Objects.equals(this.signatures, customComplianceControl.signatures) &&
        Objects.equals(this.signatureIds, customComplianceControl.signatureIds) &&
        Objects.equals(this.customSignatures, customComplianceControl.customSignatures) &&
        Objects.equals(this.customSignatureIds, customComplianceControl.customSignatureIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, identifier, description, createdAt, updatedAt, position, customComplianceStandard, customComplianceStandardId, customComplianceDomain, customComplianceDomainId, signatures, signatureIds, customSignatures, customSignatureIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomComplianceControl {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    customComplianceStandard: ").append(toIndentedString(customComplianceStandard)).append("\n");
    sb.append("    customComplianceStandardId: ").append(toIndentedString(customComplianceStandardId)).append("\n");
    sb.append("    customComplianceDomain: ").append(toIndentedString(customComplianceDomain)).append("\n");
    sb.append("    customComplianceDomainId: ").append(toIndentedString(customComplianceDomainId)).append("\n");
    sb.append("    signatures: ").append(toIndentedString(signatures)).append("\n");
    sb.append("    signatureIds: ").append(toIndentedString(signatureIds)).append("\n");
    sb.append("    customSignatures: ").append(toIndentedString(customSignatures)).append("\n");
    sb.append("    customSignatureIds: ").append(toIndentedString(customSignatureIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

