/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.CustomComplianceControl;
import io.evident.models.CustomComplianceStandard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) CustomComplianceDomain object
 */
@ApiModel(description = "A(n) CustomComplianceDomain object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class CustomComplianceDomain {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("position")
  private Integer position = null;

  @SerializedName("custom_compliance_standard")
  private CustomComplianceStandard customComplianceStandard = null;

  @SerializedName("custom_compliance_standard_id")
  private Integer customComplianceStandardId = null;

  @SerializedName("custom_compliance_controls")
  private List<CustomComplianceControl> customComplianceControls = new ArrayList<CustomComplianceControl>();

  @SerializedName("custom_compliance_control_ids")
  private List<Integer> customComplianceControlIds = new ArrayList<Integer>();

  public CustomComplianceDomain id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CustomComplianceDomain identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * The identifier of this custom domain
   * @return identifier
  **/
  @ApiModelProperty(example = "null", value = "The identifier of this custom domain")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public CustomComplianceDomain name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomComplianceDomain createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public CustomComplianceDomain updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public CustomComplianceDomain position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * The position of this custom domain within the custom standard
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "The position of this custom domain within the custom standard")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public CustomComplianceDomain customComplianceStandard(CustomComplianceStandard customComplianceStandard) {
    this.customComplianceStandard = customComplianceStandard;
    return this;
  }

   /**
   * Associated Custom Compliance Standard
   * @return customComplianceStandard
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Standard")
  public CustomComplianceStandard getCustomComplianceStandard() {
    return customComplianceStandard;
  }

  public void setCustomComplianceStandard(CustomComplianceStandard customComplianceStandard) {
    this.customComplianceStandard = customComplianceStandard;
  }

  public CustomComplianceDomain customComplianceStandardId(Integer customComplianceStandardId) {
    this.customComplianceStandardId = customComplianceStandardId;
    return this;
  }

   /**
   * Associated Custom Compliance Standard ID
   * @return customComplianceStandardId
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Standard ID")
  public Integer getCustomComplianceStandardId() {
    return customComplianceStandardId;
  }

  public void setCustomComplianceStandardId(Integer customComplianceStandardId) {
    this.customComplianceStandardId = customComplianceStandardId;
  }

  public CustomComplianceDomain customComplianceControls(List<CustomComplianceControl> customComplianceControls) {
    this.customComplianceControls = customComplianceControls;
    return this;
  }

  public CustomComplianceDomain addCustomComplianceControlsItem(CustomComplianceControl customComplianceControlsItem) {
    this.customComplianceControls.add(customComplianceControlsItem);
    return this;
  }

   /**
   * Associated Custom Compliance Controls
   * @return customComplianceControls
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Controls")
  public List<CustomComplianceControl> getCustomComplianceControls() {
    return customComplianceControls;
  }

  public void setCustomComplianceControls(List<CustomComplianceControl> customComplianceControls) {
    this.customComplianceControls = customComplianceControls;
  }

  public CustomComplianceDomain customComplianceControlIds(List<Integer> customComplianceControlIds) {
    this.customComplianceControlIds = customComplianceControlIds;
    return this;
  }

  public CustomComplianceDomain addCustomComplianceControlIdsItem(Integer customComplianceControlIdsItem) {
    this.customComplianceControlIds.add(customComplianceControlIdsItem);
    return this;
  }

   /**
   * Associated Custom Compliance Controls IDs
   * @return customComplianceControlIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Compliance Controls IDs")
  public List<Integer> getCustomComplianceControlIds() {
    return customComplianceControlIds;
  }

  public void setCustomComplianceControlIds(List<Integer> customComplianceControlIds) {
    this.customComplianceControlIds = customComplianceControlIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomComplianceDomain customComplianceDomain = (CustomComplianceDomain) o;
    return Objects.equals(this.id, customComplianceDomain.id) &&
        Objects.equals(this.identifier, customComplianceDomain.identifier) &&
        Objects.equals(this.name, customComplianceDomain.name) &&
        Objects.equals(this.createdAt, customComplianceDomain.createdAt) &&
        Objects.equals(this.updatedAt, customComplianceDomain.updatedAt) &&
        Objects.equals(this.position, customComplianceDomain.position) &&
        Objects.equals(this.customComplianceStandard, customComplianceDomain.customComplianceStandard) &&
        Objects.equals(this.customComplianceStandardId, customComplianceDomain.customComplianceStandardId) &&
        Objects.equals(this.customComplianceControls, customComplianceDomain.customComplianceControls) &&
        Objects.equals(this.customComplianceControlIds, customComplianceDomain.customComplianceControlIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, identifier, name, createdAt, updatedAt, position, customComplianceStandard, customComplianceStandardId, customComplianceControls, customComplianceControlIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomComplianceDomain {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    customComplianceStandard: ").append(toIndentedString(customComplianceStandard)).append("\n");
    sb.append("    customComplianceStandardId: ").append(toIndentedString(customComplianceStandardId)).append("\n");
    sb.append("    customComplianceControls: ").append(toIndentedString(customComplianceControls)).append("\n");
    sb.append("    customComplianceControlIds: ").append(toIndentedString(customComplianceControlIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

