/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) ExportedReport object
 */
@ApiModel(description = "A(n) ExportedReport object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class ExportedReport {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("user_id")
  private Integer userId = null;

  @SerializedName("report_ids")
  private List<Integer> reportIds = new ArrayList<Integer>();

  @SerializedName("format")
  private String format = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("file_name")
  private String fileName = null;

  @SerializedName("filter")
  private Object filter = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("user")
  private User user = null;

  public ExportedReport id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ExportedReport userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Associated User ID
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "Associated User ID")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public ExportedReport reportIds(List<Integer> reportIds) {
    this.reportIds = reportIds;
    return this;
  }

  public ExportedReport addReportIdsItem(Integer reportIdsItem) {
    this.reportIds.add(reportIdsItem);
    return this;
  }

   /**
   * An array of report IDs to export alerts for
   * @return reportIds
  **/
  @ApiModelProperty(example = "null", value = "An array of report IDs to export alerts for")
  public List<Integer> getReportIds() {
    return reportIds;
  }

  public void setReportIds(List<Integer> reportIds) {
    this.reportIds = reportIds;
  }

  public ExportedReport format(String format) {
    this.format = format;
    return this;
  }

   /**
   * The file format of the export. Valid values are csv, json, pdf
   * @return format
  **/
  @ApiModelProperty(example = "null", value = "The file format of the export. Valid values are csv, json, pdf")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public ExportedReport url(String url) {
    this.url = url;
    return this;
  }

   /**
   * A temporary URL where the file can be accessed
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "A temporary URL where the file can be accessed")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ExportedReport fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * The name of the file
   * @return fileName
  **/
  @ApiModelProperty(example = "null", value = "The name of the file")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public ExportedReport filter(Object filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Params used to filter the alerts that will be exported
   * @return filter
  **/
  @ApiModelProperty(example = "null", value = "Params used to filter the alerts that will be exported")
  public Object getFilter() {
    return filter;
  }

  public void setFilter(Object filter) {
    this.filter = filter;
  }

  public ExportedReport createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ExportedReport updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ExportedReport user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Associated User
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "Associated User")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportedReport exportedReport = (ExportedReport) o;
    return Objects.equals(this.id, exportedReport.id) &&
        Objects.equals(this.userId, exportedReport.userId) &&
        Objects.equals(this.reportIds, exportedReport.reportIds) &&
        Objects.equals(this.format, exportedReport.format) &&
        Objects.equals(this.url, exportedReport.url) &&
        Objects.equals(this.fileName, exportedReport.fileName) &&
        Objects.equals(this.filter, exportedReport.filter) &&
        Objects.equals(this.createdAt, exportedReport.createdAt) &&
        Objects.equals(this.updatedAt, exportedReport.updatedAt) &&
        Objects.equals(this.user, exportedReport.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, reportIds, format, url, fileName, filter, createdAt, updatedAt, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportedReport {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    reportIds: ").append(toIndentedString(reportIds)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

