/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.ExternalAccount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * A(n) ExternalAccountAmazonIAM object
 */
@ApiModel(description = "A(n) ExternalAccountAmazonIAM object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class ExternalAccountAmazonIAM {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("account")
  private String account = null;

  @SerializedName("arn")
  private String arn = null;

  @SerializedName("cloudtrail_name")
  private String cloudtrailName = null;

  @SerializedName("external_id")
  private String externalId = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("external_account")
  private ExternalAccount externalAccount = null;

  @SerializedName("external_account_id")
  private Integer externalAccountId = null;

  public ExternalAccountAmazonIAM id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ExternalAccountAmazonIAM account(String account) {
    this.account = account;
    return this;
  }

   /**
   * The AWS account number
   * @return account
  **/
  @ApiModelProperty(example = "null", value = "The AWS account number")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public ExternalAccountAmazonIAM arn(String arn) {
    this.arn = arn;
    return this;
  }

   /**
   * Amazon Resource Name for the IAM role
   * @return arn
  **/
  @ApiModelProperty(example = "null", value = "Amazon Resource Name for the IAM role")
  public String getArn() {
    return arn;
  }

  public void setArn(String arn) {
    this.arn = arn;
  }

  public ExternalAccountAmazonIAM cloudtrailName(String cloudtrailName) {
    this.cloudtrailName = cloudtrailName;
    return this;
  }

   /**
   * Cloudtrail Name
   * @return cloudtrailName
  **/
  @ApiModelProperty(example = "null", value = "Cloudtrail Name")
  public String getCloudtrailName() {
    return cloudtrailName;
  }

  public void setCloudtrailName(String cloudtrailName) {
    this.cloudtrailName = cloudtrailName;
  }

  public ExternalAccountAmazonIAM externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * External Identifier set on the role
   * @return externalId
  **/
  @ApiModelProperty(example = "null", value = "External Identifier set on the role")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ExternalAccountAmazonIAM createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ExternalAccountAmazonIAM updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ExternalAccountAmazonIAM externalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
    return this;
  }

   /**
   * Associated External Account
   * @return externalAccount
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account")
  public ExternalAccount getExternalAccount() {
    return externalAccount;
  }

  public void setExternalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
  }

  public ExternalAccountAmazonIAM externalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
    return this;
  }

   /**
   * Associated External Account ID
   * @return externalAccountId
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account ID")
  public Integer getExternalAccountId() {
    return externalAccountId;
  }

  public void setExternalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountAmazonIAM externalAccountAmazonIAM = (ExternalAccountAmazonIAM) o;
    return Objects.equals(this.id, externalAccountAmazonIAM.id) &&
        Objects.equals(this.account, externalAccountAmazonIAM.account) &&
        Objects.equals(this.arn, externalAccountAmazonIAM.arn) &&
        Objects.equals(this.cloudtrailName, externalAccountAmazonIAM.cloudtrailName) &&
        Objects.equals(this.externalId, externalAccountAmazonIAM.externalId) &&
        Objects.equals(this.createdAt, externalAccountAmazonIAM.createdAt) &&
        Objects.equals(this.updatedAt, externalAccountAmazonIAM.updatedAt) &&
        Objects.equals(this.externalAccount, externalAccountAmazonIAM.externalAccount) &&
        Objects.equals(this.externalAccountId, externalAccountAmazonIAM.externalAccountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, account, arn, cloudtrailName, externalId, createdAt, updatedAt, externalAccount, externalAccountId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccountAmazonIAM {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    arn: ").append(toIndentedString(arn)).append("\n");
    sb.append("    cloudtrailName: ").append(toIndentedString(cloudtrailName)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    externalAccount: ").append(toIndentedString(externalAccount)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

