/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A(n) ExternalAccountUserAttributionChannel object
 */
@ApiModel(description = "A(n) ExternalAccountUserAttributionChannel object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class ExternalAccountUserAttributionChannel {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("external_account_id")
  private Integer externalAccountId = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("url")
  private String url = null;

  public ExternalAccountUserAttributionChannel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ExternalAccountUserAttributionChannel externalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
    return this;
  }

   /**
   * The ID of the external account this channel is for
   * @return externalAccountId
  **/
  @ApiModelProperty(example = "null", value = "The ID of the external account this channel is for")
  public Integer getExternalAccountId() {
    return externalAccountId;
  }

  public void setExternalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public ExternalAccountUserAttributionChannel active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * If the channel is active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "If the channel is active")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public ExternalAccountUserAttributionChannel url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL for the channel.  It is only returned when first created.
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "The URL for the channel.  It is only returned when first created.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountUserAttributionChannel externalAccountUserAttributionChannel = (ExternalAccountUserAttributionChannel) o;
    return Objects.equals(this.id, externalAccountUserAttributionChannel.id) &&
        Objects.equals(this.externalAccountId, externalAccountUserAttributionChannel.externalAccountId) &&
        Objects.equals(this.active, externalAccountUserAttributionChannel.active) &&
        Objects.equals(this.url, externalAccountUserAttributionChannel.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalAccountId, active, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccountUserAttributionChannel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

