/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.AzureGroup;
import io.evident.models.ExternalAccountAmazonIAM;
import io.evident.models.ScanInterval;
import io.evident.models.Signature;
import io.evident.models.Suppression;
import io.evident.models.Team;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) ExternalAccount object
 */
@ApiModel(description = "A(n) ExternalAccount object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class ExternalAccount {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("provider")
  private String provider = null;

  @SerializedName("team")
  private Team team = null;

  @SerializedName("team_id")
  private Integer teamId = null;

  @SerializedName("scan_intervals")
  private List<ScanInterval> scanIntervals = new ArrayList<ScanInterval>();

  @SerializedName("scan_interval_ids")
  private List<Integer> scanIntervalIds = new ArrayList<Integer>();

  @SerializedName("disabled_signatures")
  private List<Signature> disabledSignatures = new ArrayList<Signature>();

  @SerializedName("disabled_signature_ids")
  private List<Integer> disabledSignatureIds = new ArrayList<Integer>();

  @SerializedName("suppressions")
  private List<Suppression> suppressions = new ArrayList<Suppression>();

  @SerializedName("suppression_ids")
  private List<Integer> suppressionIds = new ArrayList<Integer>();

  @SerializedName("azure_group")
  private AzureGroup azureGroup = null;

  @SerializedName("azure_group_id")
  private Integer azureGroupId = null;

  @SerializedName("credentials")
  private ExternalAccountAmazonIAM credentials = null;

  @SerializedName("credentials_id")
  private Integer credentialsId = null;

  public ExternalAccount id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ExternalAccount createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ExternalAccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExternalAccount updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ExternalAccount provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * The cloud provider this account is for
   * @return provider
  **/
  @ApiModelProperty(example = "null", value = "The cloud provider this account is for")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public ExternalAccount team(Team team) {
    this.team = team;
    return this;
  }

   /**
   * Associated Team
   * @return team
  **/
  @ApiModelProperty(example = "null", value = "Associated Team")
  public Team getTeam() {
    return team;
  }

  public void setTeam(Team team) {
    this.team = team;
  }

  public ExternalAccount teamId(Integer teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Associated Team ID
   * @return teamId
  **/
  @ApiModelProperty(example = "null", value = "Associated Team ID")
  public Integer getTeamId() {
    return teamId;
  }

  public void setTeamId(Integer teamId) {
    this.teamId = teamId;
  }

  public ExternalAccount scanIntervals(List<ScanInterval> scanIntervals) {
    this.scanIntervals = scanIntervals;
    return this;
  }

  public ExternalAccount addScanIntervalsItem(ScanInterval scanIntervalsItem) {
    this.scanIntervals.add(scanIntervalsItem);
    return this;
  }

   /**
   * Associated Scan Intervals
   * @return scanIntervals
  **/
  @ApiModelProperty(example = "null", value = "Associated Scan Intervals")
  public List<ScanInterval> getScanIntervals() {
    return scanIntervals;
  }

  public void setScanIntervals(List<ScanInterval> scanIntervals) {
    this.scanIntervals = scanIntervals;
  }

  public ExternalAccount scanIntervalIds(List<Integer> scanIntervalIds) {
    this.scanIntervalIds = scanIntervalIds;
    return this;
  }

  public ExternalAccount addScanIntervalIdsItem(Integer scanIntervalIdsItem) {
    this.scanIntervalIds.add(scanIntervalIdsItem);
    return this;
  }

   /**
   * Associated Scan Intervals IDs
   * @return scanIntervalIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Scan Intervals IDs")
  public List<Integer> getScanIntervalIds() {
    return scanIntervalIds;
  }

  public void setScanIntervalIds(List<Integer> scanIntervalIds) {
    this.scanIntervalIds = scanIntervalIds;
  }

  public ExternalAccount disabledSignatures(List<Signature> disabledSignatures) {
    this.disabledSignatures = disabledSignatures;
    return this;
  }

  public ExternalAccount addDisabledSignaturesItem(Signature disabledSignaturesItem) {
    this.disabledSignatures.add(disabledSignaturesItem);
    return this;
  }

   /**
   * Associated Disabled Signatures
   * @return disabledSignatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Disabled Signatures")
  public List<Signature> getDisabledSignatures() {
    return disabledSignatures;
  }

  public void setDisabledSignatures(List<Signature> disabledSignatures) {
    this.disabledSignatures = disabledSignatures;
  }

  public ExternalAccount disabledSignatureIds(List<Integer> disabledSignatureIds) {
    this.disabledSignatureIds = disabledSignatureIds;
    return this;
  }

  public ExternalAccount addDisabledSignatureIdsItem(Integer disabledSignatureIdsItem) {
    this.disabledSignatureIds.add(disabledSignatureIdsItem);
    return this;
  }

   /**
   * Associated Disabled Signatures IDs
   * @return disabledSignatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Disabled Signatures IDs")
  public List<Integer> getDisabledSignatureIds() {
    return disabledSignatureIds;
  }

  public void setDisabledSignatureIds(List<Integer> disabledSignatureIds) {
    this.disabledSignatureIds = disabledSignatureIds;
  }

  public ExternalAccount suppressions(List<Suppression> suppressions) {
    this.suppressions = suppressions;
    return this;
  }

  public ExternalAccount addSuppressionsItem(Suppression suppressionsItem) {
    this.suppressions.add(suppressionsItem);
    return this;
  }

   /**
   * Associated Suppressions
   * @return suppressions
  **/
  @ApiModelProperty(example = "null", value = "Associated Suppressions")
  public List<Suppression> getSuppressions() {
    return suppressions;
  }

  public void setSuppressions(List<Suppression> suppressions) {
    this.suppressions = suppressions;
  }

  public ExternalAccount suppressionIds(List<Integer> suppressionIds) {
    this.suppressionIds = suppressionIds;
    return this;
  }

  public ExternalAccount addSuppressionIdsItem(Integer suppressionIdsItem) {
    this.suppressionIds.add(suppressionIdsItem);
    return this;
  }

   /**
   * Associated Suppressions IDs
   * @return suppressionIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Suppressions IDs")
  public List<Integer> getSuppressionIds() {
    return suppressionIds;
  }

  public void setSuppressionIds(List<Integer> suppressionIds) {
    this.suppressionIds = suppressionIds;
  }

  public ExternalAccount azureGroup(AzureGroup azureGroup) {
    this.azureGroup = azureGroup;
    return this;
  }

   /**
   * Associated Azure Group
   * @return azureGroup
  **/
  @ApiModelProperty(example = "null", value = "Associated Azure Group")
  public AzureGroup getAzureGroup() {
    return azureGroup;
  }

  public void setAzureGroup(AzureGroup azureGroup) {
    this.azureGroup = azureGroup;
  }

  public ExternalAccount azureGroupId(Integer azureGroupId) {
    this.azureGroupId = azureGroupId;
    return this;
  }

   /**
   * Associated Azure Group ID
   * @return azureGroupId
  **/
  @ApiModelProperty(example = "null", value = "Associated Azure Group ID")
  public Integer getAzureGroupId() {
    return azureGroupId;
  }

  public void setAzureGroupId(Integer azureGroupId) {
    this.azureGroupId = azureGroupId;
  }

  public ExternalAccount credentials(ExternalAccountAmazonIAM credentials) {
    this.credentials = credentials;
    return this;
  }

   /**
   * Associated Credentials
   * @return credentials
  **/
  @ApiModelProperty(example = "null", value = "Associated Credentials")
  public ExternalAccountAmazonIAM getCredentials() {
    return credentials;
  }

  public void setCredentials(ExternalAccountAmazonIAM credentials) {
    this.credentials = credentials;
  }

  public ExternalAccount credentialsId(Integer credentialsId) {
    this.credentialsId = credentialsId;
    return this;
  }

   /**
   * Associated Credentials ID
   * @return credentialsId
  **/
  @ApiModelProperty(example = "null", value = "Associated Credentials ID")
  public Integer getCredentialsId() {
    return credentialsId;
  }

  public void setCredentialsId(Integer credentialsId) {
    this.credentialsId = credentialsId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccount externalAccount = (ExternalAccount) o;
    return Objects.equals(this.id, externalAccount.id) &&
        Objects.equals(this.createdAt, externalAccount.createdAt) &&
        Objects.equals(this.name, externalAccount.name) &&
        Objects.equals(this.updatedAt, externalAccount.updatedAt) &&
        Objects.equals(this.provider, externalAccount.provider) &&
        Objects.equals(this.team, externalAccount.team) &&
        Objects.equals(this.teamId, externalAccount.teamId) &&
        Objects.equals(this.scanIntervals, externalAccount.scanIntervals) &&
        Objects.equals(this.scanIntervalIds, externalAccount.scanIntervalIds) &&
        Objects.equals(this.disabledSignatures, externalAccount.disabledSignatures) &&
        Objects.equals(this.disabledSignatureIds, externalAccount.disabledSignatureIds) &&
        Objects.equals(this.suppressions, externalAccount.suppressions) &&
        Objects.equals(this.suppressionIds, externalAccount.suppressionIds) &&
        Objects.equals(this.azureGroup, externalAccount.azureGroup) &&
        Objects.equals(this.azureGroupId, externalAccount.azureGroupId) &&
        Objects.equals(this.credentials, externalAccount.credentials) &&
        Objects.equals(this.credentialsId, externalAccount.credentialsId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, name, updatedAt, provider, team, teamId, scanIntervals, scanIntervalIds, disabledSignatures, disabledSignatureIds, suppressions, suppressionIds, azureGroup, azureGroupId, credentials, credentialsId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    scanIntervals: ").append(toIndentedString(scanIntervals)).append("\n");
    sb.append("    scanIntervalIds: ").append(toIndentedString(scanIntervalIds)).append("\n");
    sb.append("    disabledSignatures: ").append(toIndentedString(disabledSignatures)).append("\n");
    sb.append("    disabledSignatureIds: ").append(toIndentedString(disabledSignatureIds)).append("\n");
    sb.append("    suppressions: ").append(toIndentedString(suppressions)).append("\n");
    sb.append("    suppressionIds: ").append(toIndentedString(suppressionIds)).append("\n");
    sb.append("    azureGroup: ").append(toIndentedString(azureGroup)).append("\n");
    sb.append("    azureGroupId: ").append(toIndentedString(azureGroupId)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    credentialsId: ").append(toIndentedString(credentialsId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

