/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.ExternalAccount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * A(n) ExternalAccountAzure object
 */
@ApiModel(description = "A(n) ExternalAccountAzure object")

public class ExternalAccountAzure {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("subscription_id")
  private String subscriptionId = null;

  @SerializedName("client_id")
  private String clientId = null;

  @SerializedName("tenant_id")
  private String tenantId = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("last_message_received_at")
  private DateTime lastMessageReceivedAt = null;

  @SerializedName("app_key")
  private String appKey = null;

  @SerializedName("channel_url")
  private String channelUrl = null;

  @SerializedName("channel_active")
  private Boolean channelActive = null;

  @SerializedName("external_account")
  private ExternalAccount externalAccount = null;

  @SerializedName("external_account_id")
  private Integer externalAccountId = null;

  public ExternalAccountAzure id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ExternalAccountAzure subscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * Azure subscription ID
   * @return subscriptionId
  **/
  @ApiModelProperty(example = "null", value = "Azure subscription ID")
  public String getSubscriptionId() {
    return subscriptionId;
  }

  public void setSubscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }

  public ExternalAccountAzure clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Azure client ID
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "Azure client ID")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ExternalAccountAzure tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Azure tenant ID
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "Azure tenant ID")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public ExternalAccountAzure createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ExternalAccountAzure updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ExternalAccountAzure lastMessageReceivedAt(DateTime lastMessageReceivedAt) {
    this.lastMessageReceivedAt = lastMessageReceivedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the last event was received from Azure. This is updated hourly.
   * @return lastMessageReceivedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the last event was received from Azure. This is updated hourly.")
  public DateTime getLastMessageReceivedAt() {
    return lastMessageReceivedAt;
  }

  public void setLastMessageReceivedAt(DateTime lastMessageReceivedAt) {
    this.lastMessageReceivedAt = lastMessageReceivedAt;
  }

  public ExternalAccountAzure appKey(String appKey) {
    this.appKey = appKey;
    return this;
  }

   /**
   * Azure app key
   * @return appKey
  **/
  @ApiModelProperty(example = "null", value = "Azure app key")
  public String getAppKey() {
    return appKey;
  }

  public void setAppKey(String appKey) {
    this.appKey = appKey;
  }

  public ExternalAccountAzure channelUrl(String channelUrl) {
    this.channelUrl = channelUrl;
    return this;
  }

   /**
   * The URL for the azure account channel.  It is only returned when first created or when reset.
   * @return channelUrl
  **/
  @ApiModelProperty(example = "null", value = "The URL for the azure account channel.  It is only returned when first created or when reset.")
  public String getChannelUrl() {
    return channelUrl;
  }

  public void setChannelUrl(String channelUrl) {
    this.channelUrl = channelUrl;
  }

  public ExternalAccountAzure channelActive(Boolean channelActive) {
    this.channelActive = channelActive;
    return this;
  }

   /**
   * Returns true if the channel is active
   * @return channelActive
  **/
  @ApiModelProperty(example = "null", value = "Returns true if the channel is active")
  public Boolean getChannelActive() {
    return channelActive;
  }

  public void setChannelActive(Boolean channelActive) {
    this.channelActive = channelActive;
  }

  public ExternalAccountAzure externalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
    return this;
  }

   /**
   * Associated External Account
   * @return externalAccount
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account")
  public ExternalAccount getExternalAccount() {
    return externalAccount;
  }

  public void setExternalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
  }

  public ExternalAccountAzure externalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
    return this;
  }

   /**
   * Associated External Account ID
   * @return externalAccountId
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account ID")
  public Integer getExternalAccountId() {
    return externalAccountId;
  }

  public void setExternalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountAzure externalAccountAzure = (ExternalAccountAzure) o;
    return Objects.equals(this.id, externalAccountAzure.id) &&
        Objects.equals(this.subscriptionId, externalAccountAzure.subscriptionId) &&
        Objects.equals(this.clientId, externalAccountAzure.clientId) &&
        Objects.equals(this.tenantId, externalAccountAzure.tenantId) &&
        Objects.equals(this.createdAt, externalAccountAzure.createdAt) &&
        Objects.equals(this.updatedAt, externalAccountAzure.updatedAt) &&
        Objects.equals(this.lastMessageReceivedAt, externalAccountAzure.lastMessageReceivedAt) &&
        Objects.equals(this.appKey, externalAccountAzure.appKey) &&
        Objects.equals(this.channelUrl, externalAccountAzure.channelUrl) &&
        Objects.equals(this.channelActive, externalAccountAzure.channelActive) &&
        Objects.equals(this.externalAccount, externalAccountAzure.externalAccount) &&
        Objects.equals(this.externalAccountId, externalAccountAzure.externalAccountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subscriptionId, clientId, tenantId, createdAt, updatedAt, lastMessageReceivedAt, appKey, channelUrl, channelActive, externalAccount, externalAccountId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccountAzure {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    lastMessageReceivedAt: ").append(toIndentedString(lastMessageReceivedAt)).append("\n");
    sb.append("    appKey: ").append(toIndentedString(appKey)).append("\n");
    sb.append("    channelUrl: ").append(toIndentedString(channelUrl)).append("\n");
    sb.append("    channelActive: ").append(toIndentedString(channelActive)).append("\n");
    sb.append("    externalAccount: ").append(toIndentedString(externalAccount)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

