/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.CustomSignature;
import io.evident.models.ExternalAccount;
import io.evident.models.Organization;
import io.evident.models.Service;
import io.evident.models.Signature;
import io.evident.models.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) Integration object
 */
@ApiModel(description = "A(n) Integration object")

public class Integration {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("statuses")
  private List<String> statuses = new ArrayList<String>();

  @SerializedName("name")
  private String name = null;

  @SerializedName("all_high_risk")
  private Boolean allHighRisk = null;

  @SerializedName("all_medium_risk")
  private Boolean allMediumRisk = null;

  @SerializedName("all_low_risk")
  private Boolean allLowRisk = null;

  @SerializedName("send_updates")
  private Boolean sendUpdates = null;

  @SerializedName("error_messages")
  private List<String> errorMessages = new ArrayList<String>();

  @SerializedName("last_throttled_at")
  private DateTime lastThrottledAt = null;

  @SerializedName("send_when_suppressed")
  private Boolean sendWhenSuppressed = null;

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("organization_id")
  private Integer organizationId = null;

  @SerializedName("creator")
  private User creator = null;

  @SerializedName("creator_id")
  private Integer creatorId = null;

  @SerializedName("service")
  private Service service = null;

  @SerializedName("service_id")
  private Integer serviceId = null;

  @SerializedName("external_accounts")
  private List<ExternalAccount> externalAccounts = new ArrayList<ExternalAccount>();

  @SerializedName("external_account_ids")
  private List<Integer> externalAccountIds = new ArrayList<Integer>();

  @SerializedName("signatures")
  private List<Signature> signatures = new ArrayList<Signature>();

  @SerializedName("signature_ids")
  private List<Integer> signatureIds = new ArrayList<Integer>();

  @SerializedName("custom_signatures")
  private List<CustomSignature> customSignatures = new ArrayList<CustomSignature>();

  @SerializedName("custom_signature_ids")
  private List<Integer> customSignatureIds = new ArrayList<Integer>();

  public Integration id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integration createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Integration updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Integration state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The state the integration is in. Valid values are setup, active, error, disabled
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "The state the integration is in. Valid values are setup, active, error, disabled")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Integration statuses(List<String> statuses) {
    this.statuses = statuses;
    return this;
  }

  public Integration addStatusesItem(String statusesItem) {
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * Only send alerts that have the status in this list. Valid values are fail, warn, error, pass, info
   * @return statuses
  **/
  @ApiModelProperty(example = "null", value = "Only send alerts that have the status in this list. Valid values are fail, warn, error, pass, info")
  public List<String> getStatuses() {
    return statuses;
  }

  public void setStatuses(List<String> statuses) {
    this.statuses = statuses;
  }

  public Integration name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the integration
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of the integration")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Integration allHighRisk(Boolean allHighRisk) {
    this.allHighRisk = allHighRisk;
    return this;
  }

   /**
   * Send all high risk alerts
   * @return allHighRisk
  **/
  @ApiModelProperty(example = "null", value = "Send all high risk alerts")
  public Boolean getAllHighRisk() {
    return allHighRisk;
  }

  public void setAllHighRisk(Boolean allHighRisk) {
    this.allHighRisk = allHighRisk;
  }

  public Integration allMediumRisk(Boolean allMediumRisk) {
    this.allMediumRisk = allMediumRisk;
    return this;
  }

   /**
   * Send all medium risk alerts
   * @return allMediumRisk
  **/
  @ApiModelProperty(example = "null", value = "Send all medium risk alerts")
  public Boolean getAllMediumRisk() {
    return allMediumRisk;
  }

  public void setAllMediumRisk(Boolean allMediumRisk) {
    this.allMediumRisk = allMediumRisk;
  }

  public Integration allLowRisk(Boolean allLowRisk) {
    this.allLowRisk = allLowRisk;
    return this;
  }

   /**
   * Send all low risk alerts
   * @return allLowRisk
  **/
  @ApiModelProperty(example = "null", value = "Send all low risk alerts")
  public Boolean getAllLowRisk() {
    return allLowRisk;
  }

  public void setAllLowRisk(Boolean allLowRisk) {
    this.allLowRisk = allLowRisk;
  }

  public Integration sendUpdates(Boolean sendUpdates) {
    this.sendUpdates = sendUpdates;
    return this;
  }

   /**
   * This feature enables the integration to send alerts when they are updated. When disabled, alerts will only be sent when they are initially created. When enabled, alerts will additionally be sent when a change is made such as the alert ending. An alert may end for multiple reasons.
   * @return sendUpdates
  **/
  @ApiModelProperty(example = "null", value = "This feature enables the integration to send alerts when they are updated. When disabled, alerts will only be sent when they are initially created. When enabled, alerts will additionally be sent when a change is made such as the alert ending. An alert may end for multiple reasons.")
  public Boolean getSendUpdates() {
    return sendUpdates;
  }

  public void setSendUpdates(Boolean sendUpdates) {
    this.sendUpdates = sendUpdates;
  }

  public Integration errorMessages(List<String> errorMessages) {
    this.errorMessages = errorMessages;
    return this;
  }

  public Integration addErrorMessagesItem(String errorMessagesItem) {
    this.errorMessages.add(errorMessagesItem);
    return this;
  }

   /**
   * Array of error messages
   * @return errorMessages
  **/
  @ApiModelProperty(example = "null", value = "Array of error messages")
  public List<String> getErrorMessages() {
    return errorMessages;
  }

  public void setErrorMessages(List<String> errorMessages) {
    this.errorMessages = errorMessages;
  }

  public Integration lastThrottledAt(DateTime lastThrottledAt) {
    this.lastThrottledAt = lastThrottledAt;
    return this;
  }

   /**
   * The time at which this integration was last throttled.
   * @return lastThrottledAt
  **/
  @ApiModelProperty(example = "null", value = "The time at which this integration was last throttled.")
  public DateTime getLastThrottledAt() {
    return lastThrottledAt;
  }

  public void setLastThrottledAt(DateTime lastThrottledAt) {
    this.lastThrottledAt = lastThrottledAt;
  }

  public Integration sendWhenSuppressed(Boolean sendWhenSuppressed) {
    this.sendWhenSuppressed = sendWhenSuppressed;
    return this;
  }

   /**
   * Send notifications for suppressed alerts
   * @return sendWhenSuppressed
  **/
  @ApiModelProperty(example = "null", value = "Send notifications for suppressed alerts")
  public Boolean getSendWhenSuppressed() {
    return sendWhenSuppressed;
  }

  public void setSendWhenSuppressed(Boolean sendWhenSuppressed) {
    this.sendWhenSuppressed = sendWhenSuppressed;
  }

  public Integration organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Associated Organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public Integration organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Associated Organization ID
   * @return organizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public Integration creator(User creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Associated Creator
   * @return creator
  **/
  @ApiModelProperty(example = "null", value = "Associated Creator")
  public User getCreator() {
    return creator;
  }

  public void setCreator(User creator) {
    this.creator = creator;
  }

  public Integration creatorId(Integer creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * Associated Creator ID
   * @return creatorId
  **/
  @ApiModelProperty(example = "null", value = "Associated Creator ID")
  public Integer getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(Integer creatorId) {
    this.creatorId = creatorId;
  }

  public Integration service(Service service) {
    this.service = service;
    return this;
  }

   /**
   * Associated Service
   * @return service
  **/
  @ApiModelProperty(example = "null", value = "Associated Service")
  public Service getService() {
    return service;
  }

  public void setService(Service service) {
    this.service = service;
  }

  public Integration serviceId(Integer serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Associated Service ID
   * @return serviceId
  **/
  @ApiModelProperty(example = "null", value = "Associated Service ID")
  public Integer getServiceId() {
    return serviceId;
  }

  public void setServiceId(Integer serviceId) {
    this.serviceId = serviceId;
  }

  public Integration externalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
    return this;
  }

  public Integration addExternalAccountsItem(ExternalAccount externalAccountsItem) {
    this.externalAccounts.add(externalAccountsItem);
    return this;
  }

   /**
   * Associated External Accounts
   * @return externalAccounts
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts")
  public List<ExternalAccount> getExternalAccounts() {
    return externalAccounts;
  }

  public void setExternalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
  }

  public Integration externalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
    return this;
  }

  public Integration addExternalAccountIdsItem(Integer externalAccountIdsItem) {
    this.externalAccountIds.add(externalAccountIdsItem);
    return this;
  }

   /**
   * Associated External Accounts IDs
   * @return externalAccountIds
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts IDs")
  public List<Integer> getExternalAccountIds() {
    return externalAccountIds;
  }

  public void setExternalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
  }

  public Integration signatures(List<Signature> signatures) {
    this.signatures = signatures;
    return this;
  }

  public Integration addSignaturesItem(Signature signaturesItem) {
    this.signatures.add(signaturesItem);
    return this;
  }

   /**
   * Associated Signatures
   * @return signatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Signatures")
  public List<Signature> getSignatures() {
    return signatures;
  }

  public void setSignatures(List<Signature> signatures) {
    this.signatures = signatures;
  }

  public Integration signatureIds(List<Integer> signatureIds) {
    this.signatureIds = signatureIds;
    return this;
  }

  public Integration addSignatureIdsItem(Integer signatureIdsItem) {
    this.signatureIds.add(signatureIdsItem);
    return this;
  }

   /**
   * Associated Signatures IDs
   * @return signatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Signatures IDs")
  public List<Integer> getSignatureIds() {
    return signatureIds;
  }

  public void setSignatureIds(List<Integer> signatureIds) {
    this.signatureIds = signatureIds;
  }

  public Integration customSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
    return this;
  }

  public Integration addCustomSignaturesItem(CustomSignature customSignaturesItem) {
    this.customSignatures.add(customSignaturesItem);
    return this;
  }

   /**
   * Associated Custom Signatures
   * @return customSignatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures")
  public List<CustomSignature> getCustomSignatures() {
    return customSignatures;
  }

  public void setCustomSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
  }

  public Integration customSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
    return this;
  }

  public Integration addCustomSignatureIdsItem(Integer customSignatureIdsItem) {
    this.customSignatureIds.add(customSignatureIdsItem);
    return this;
  }

   /**
   * Associated Custom Signatures IDs
   * @return customSignatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures IDs")
  public List<Integer> getCustomSignatureIds() {
    return customSignatureIds;
  }

  public void setCustomSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Integration integration = (Integration) o;
    return Objects.equals(this.id, integration.id) &&
        Objects.equals(this.createdAt, integration.createdAt) &&
        Objects.equals(this.updatedAt, integration.updatedAt) &&
        Objects.equals(this.state, integration.state) &&
        Objects.equals(this.statuses, integration.statuses) &&
        Objects.equals(this.name, integration.name) &&
        Objects.equals(this.allHighRisk, integration.allHighRisk) &&
        Objects.equals(this.allMediumRisk, integration.allMediumRisk) &&
        Objects.equals(this.allLowRisk, integration.allLowRisk) &&
        Objects.equals(this.sendUpdates, integration.sendUpdates) &&
        Objects.equals(this.errorMessages, integration.errorMessages) &&
        Objects.equals(this.lastThrottledAt, integration.lastThrottledAt) &&
        Objects.equals(this.sendWhenSuppressed, integration.sendWhenSuppressed) &&
        Objects.equals(this.organization, integration.organization) &&
        Objects.equals(this.organizationId, integration.organizationId) &&
        Objects.equals(this.creator, integration.creator) &&
        Objects.equals(this.creatorId, integration.creatorId) &&
        Objects.equals(this.service, integration.service) &&
        Objects.equals(this.serviceId, integration.serviceId) &&
        Objects.equals(this.externalAccounts, integration.externalAccounts) &&
        Objects.equals(this.externalAccountIds, integration.externalAccountIds) &&
        Objects.equals(this.signatures, integration.signatures) &&
        Objects.equals(this.signatureIds, integration.signatureIds) &&
        Objects.equals(this.customSignatures, integration.customSignatures) &&
        Objects.equals(this.customSignatureIds, integration.customSignatureIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, state, statuses, name, allHighRisk, allMediumRisk, allLowRisk, sendUpdates, errorMessages, lastThrottledAt, sendWhenSuppressed, organization, organizationId, creator, creatorId, service, serviceId, externalAccounts, externalAccountIds, signatures, signatureIds, customSignatures, customSignatureIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Integration {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allHighRisk: ").append(toIndentedString(allHighRisk)).append("\n");
    sb.append("    allMediumRisk: ").append(toIndentedString(allMediumRisk)).append("\n");
    sb.append("    allLowRisk: ").append(toIndentedString(allLowRisk)).append("\n");
    sb.append("    sendUpdates: ").append(toIndentedString(sendUpdates)).append("\n");
    sb.append("    errorMessages: ").append(toIndentedString(errorMessages)).append("\n");
    sb.append("    lastThrottledAt: ").append(toIndentedString(lastThrottledAt)).append("\n");
    sb.append("    sendWhenSuppressed: ").append(toIndentedString(sendWhenSuppressed)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    externalAccounts: ").append(toIndentedString(externalAccounts)).append("\n");
    sb.append("    externalAccountIds: ").append(toIndentedString(externalAccountIds)).append("\n");
    sb.append("    signatures: ").append(toIndentedString(signatures)).append("\n");
    sb.append("    signatureIds: ").append(toIndentedString(signatureIds)).append("\n");
    sb.append("    customSignatures: ").append(toIndentedString(customSignatures)).append("\n");
    sb.append("    customSignatureIds: ").append(toIndentedString(customSignatureIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

