/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A(n) Plan object
 */
@ApiModel(description = "A(n) Plan object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class Plan {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("max_external_accounts")
  private Integer maxExternalAccounts = null;

  @SerializedName("max_users")
  private Integer maxUsers = null;

  @SerializedName("max_custom_signatures")
  private Integer maxCustomSignatures = null;

  @SerializedName("plan_type")
  private String planType = null;

  @SerializedName("grandfathered")
  private Boolean grandfathered = null;

  public Plan id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Plan name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the plan
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The name of the plan")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Plan amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Cost of the plan per interval
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "Cost of the plan per interval")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public Plan maxExternalAccounts(Integer maxExternalAccounts) {
    this.maxExternalAccounts = maxExternalAccounts;
    return this;
  }

   /**
   * Number of external accounts allowed for this plan.
   * @return maxExternalAccounts
  **/
  @ApiModelProperty(example = "null", value = "Number of external accounts allowed for this plan.")
  public Integer getMaxExternalAccounts() {
    return maxExternalAccounts;
  }

  public void setMaxExternalAccounts(Integer maxExternalAccounts) {
    this.maxExternalAccounts = maxExternalAccounts;
  }

  public Plan maxUsers(Integer maxUsers) {
    this.maxUsers = maxUsers;
    return this;
  }

   /**
   * Number of users allowed for this plan.
   * @return maxUsers
  **/
  @ApiModelProperty(example = "null", value = "Number of users allowed for this plan.")
  public Integer getMaxUsers() {
    return maxUsers;
  }

  public void setMaxUsers(Integer maxUsers) {
    this.maxUsers = maxUsers;
  }

  public Plan maxCustomSignatures(Integer maxCustomSignatures) {
    this.maxCustomSignatures = maxCustomSignatures;
    return this;
  }

   /**
   * Number of Custom Signatures allowed for this plan.
   * @return maxCustomSignatures
  **/
  @ApiModelProperty(example = "null", value = "Number of Custom Signatures allowed for this plan.")
  public Integer getMaxCustomSignatures() {
    return maxCustomSignatures;
  }

  public void setMaxCustomSignatures(Integer maxCustomSignatures) {
    this.maxCustomSignatures = maxCustomSignatures;
  }

  public Plan planType(String planType) {
    this.planType = planType;
    return this;
  }

   /**
   * Kind of plan. Valid values are appliance, enterprise, free, stripe
   * @return planType
  **/
  @ApiModelProperty(example = "null", value = "Kind of plan. Valid values are appliance, enterprise, free, stripe")
  public String getPlanType() {
    return planType;
  }

  public void setPlanType(String planType) {
    this.planType = planType;
  }

  public Plan grandfathered(Boolean grandfathered) {
    this.grandfathered = grandfathered;
    return this;
  }

   /**
   * Changes to the plan are prohibited if grandfathered is true.
   * @return grandfathered
  **/
  @ApiModelProperty(example = "null", value = "Changes to the plan are prohibited if grandfathered is true.")
  public Boolean getGrandfathered() {
    return grandfathered;
  }

  public void setGrandfathered(Boolean grandfathered) {
    this.grandfathered = grandfathered;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plan plan = (Plan) o;
    return Objects.equals(this.id, plan.id) &&
        Objects.equals(this.name, plan.name) &&
        Objects.equals(this.amount, plan.amount) &&
        Objects.equals(this.maxExternalAccounts, plan.maxExternalAccounts) &&
        Objects.equals(this.maxUsers, plan.maxUsers) &&
        Objects.equals(this.maxCustomSignatures, plan.maxCustomSignatures) &&
        Objects.equals(this.planType, plan.planType) &&
        Objects.equals(this.grandfathered, plan.grandfathered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, amount, maxExternalAccounts, maxUsers, maxCustomSignatures, planType, grandfathered);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plan {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    maxExternalAccounts: ").append(toIndentedString(maxExternalAccounts)).append("\n");
    sb.append("    maxUsers: ").append(toIndentedString(maxUsers)).append("\n");
    sb.append("    maxCustomSignatures: ").append(toIndentedString(maxCustomSignatures)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    grandfathered: ").append(toIndentedString(grandfathered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

