/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.Alert;
import io.evident.models.ExternalAccount;
import io.evident.models.Stat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) Report object
 */
@ApiModel(description = "A(n) Report object")

public class Report {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("external_account")
  private ExternalAccount externalAccount = null;

  @SerializedName("external_account_id")
  private Integer externalAccountId = null;

  @SerializedName("alerts")
  private List<Alert> alerts = new ArrayList<Alert>();

  @SerializedName("stat")
  private Stat stat = null;

  public Report id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Report createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Report status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the report. Valid values are queued, processing, partial, complete, failed
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Status of the report. Valid values are queued, processing, partial, complete, failed")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Report updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Report externalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
    return this;
  }

   /**
   * Associated External Account
   * @return externalAccount
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account")
  public ExternalAccount getExternalAccount() {
    return externalAccount;
  }

  public void setExternalAccount(ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
  }

  public Report externalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
    return this;
  }

   /**
   * Associated External Account ID
   * @return externalAccountId
  **/
  @ApiModelProperty(example = "null", value = "Associated External Account ID")
  public Integer getExternalAccountId() {
    return externalAccountId;
  }

  public void setExternalAccountId(Integer externalAccountId) {
    this.externalAccountId = externalAccountId;
  }

  public Report alerts(List<Alert> alerts) {
    this.alerts = alerts;
    return this;
  }

  public Report addAlertsItem(Alert alertsItem) {
    this.alerts.add(alertsItem);
    return this;
  }

   /**
   * Associated Alerts
   * @return alerts
  **/
  @ApiModelProperty(example = "null", value = "Associated Alerts")
  public List<Alert> getAlerts() {
    return alerts;
  }

  public void setAlerts(List<Alert> alerts) {
    this.alerts = alerts;
  }

  public Report stat(Stat stat) {
    this.stat = stat;
    return this;
  }

   /**
   * Associated Stat
   * @return stat
  **/
  @ApiModelProperty(example = "null", value = "Associated Stat")
  public Stat getStat() {
    return stat;
  }

  public void setStat(Stat stat) {
    this.stat = stat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Report report = (Report) o;
    return Objects.equals(this.id, report.id) &&
        Objects.equals(this.createdAt, report.createdAt) &&
        Objects.equals(this.status, report.status) &&
        Objects.equals(this.updatedAt, report.updatedAt) &&
        Objects.equals(this.externalAccount, report.externalAccount) &&
        Objects.equals(this.externalAccountId, report.externalAccountId) &&
        Objects.equals(this.alerts, report.alerts) &&
        Objects.equals(this.stat, report.stat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, status, updatedAt, externalAccount, externalAccountId, alerts, stat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Report {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    externalAccount: ").append(toIndentedString(externalAccount)).append("\n");
    sb.append("    externalAccountId: ").append(toIndentedString(externalAccountId)).append("\n");
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

