/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.ExternalAccount;
import io.evident.models.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) ScheduledExport object
 */
@ApiModel(description = "A(n) ScheduledExport object")

public class ScheduledExport {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("frequency")
  private String frequency = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("filter")
  private Object filter = null;

  @SerializedName("hour")
  private Integer hour = null;

  @SerializedName("day")
  private String day = null;

  @SerializedName("time_zone")
  private String timeZone = null;

  @SerializedName("recipients")
  private List<String> recipients = new ArrayList<String>();

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("external_accounts")
  private List<ExternalAccount> externalAccounts = new ArrayList<ExternalAccount>();

  @SerializedName("external_account_ids")
  private List<Integer> externalAccountIds = new ArrayList<Integer>();

  @SerializedName("creator")
  private User creator = null;

  @SerializedName("creator_id")
  private Integer creatorId = null;

  public ScheduledExport id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ScheduledExport name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A name that describes the export
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "A name that describes the export")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScheduledExport frequency(String frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Frequency of the export. Valid values are weekly, daily, monthly
   * @return frequency
  **/
  @ApiModelProperty(example = "null", value = "Frequency of the export. Valid values are weekly, daily, monthly")
  public String getFrequency() {
    return frequency;
  }

  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }

  public ScheduledExport status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the scheduled export. Valid values are active, unsubscribed, disabled
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Status of the scheduled export. Valid values are active, unsubscribed, disabled")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ScheduledExport filter(Object filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Params used to filter the alerts that will be exported
   * @return filter
  **/
  @ApiModelProperty(example = "null", value = "Params used to filter the alerts that will be exported")
  public Object getFilter() {
    return filter;
  }

  public void setFilter(Object filter) {
    this.filter = filter;
  }

  public ScheduledExport hour(Integer hour) {
    this.hour = hour;
    return this;
  }

   /**
   * Hour of the day to perform the export. Valid values are 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
   * @return hour
  **/
  @ApiModelProperty(example = "null", value = "Hour of the day to perform the export. Valid values are 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23")
  public Integer getHour() {
    return hour;
  }

  public void setHour(Integer hour) {
    this.hour = hour;
  }

  public ScheduledExport day(String day) {
    this.day = day;
    return this;
  }

   /**
   * Day of the week or day of the month to perform the export.  Allowed Values: Daily: nil - Weekly: sunday, monday, tuesday, wednesday, thursday, friday, or saturday - Monthly: 1 to 31. Valid values are sunday, monday, tuesday, wednesday, thursday, friday, saturday, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
   * @return day
  **/
  @ApiModelProperty(example = "null", value = "Day of the week or day of the month to perform the export.  Allowed Values: Daily: nil - Weekly: sunday, monday, tuesday, wednesday, thursday, friday, or saturday - Monthly: 1 to 31. Valid values are sunday, monday, tuesday, wednesday, thursday, friday, saturday, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31")
  public String getDay() {
    return day;
  }

  public void setDay(String day) {
    this.day = day;
  }

  public ScheduledExport timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Time zone to use when calculating hour and day
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "Time zone to use when calculating hour and day")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public ScheduledExport recipients(List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public ScheduledExport addRecipientsItem(String recipientsItem) {
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Email addresses the export will be sent to
   * @return recipients
  **/
  @ApiModelProperty(example = "null", value = "Email addresses the export will be sent to")
  public List<String> getRecipients() {
    return recipients;
  }

  public void setRecipients(List<String> recipients) {
    this.recipients = recipients;
  }

  public ScheduledExport createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ScheduledExport updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ScheduledExport externalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
    return this;
  }

  public ScheduledExport addExternalAccountsItem(ExternalAccount externalAccountsItem) {
    this.externalAccounts.add(externalAccountsItem);
    return this;
  }

   /**
   * Associated External Accounts
   * @return externalAccounts
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts")
  public List<ExternalAccount> getExternalAccounts() {
    return externalAccounts;
  }

  public void setExternalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
  }

  public ScheduledExport externalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
    return this;
  }

  public ScheduledExport addExternalAccountIdsItem(Integer externalAccountIdsItem) {
    this.externalAccountIds.add(externalAccountIdsItem);
    return this;
  }

   /**
   * Associated External Accounts IDs
   * @return externalAccountIds
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts IDs")
  public List<Integer> getExternalAccountIds() {
    return externalAccountIds;
  }

  public void setExternalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
  }

  public ScheduledExport creator(User creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Associated Creator
   * @return creator
  **/
  @ApiModelProperty(example = "null", value = "Associated Creator")
  public User getCreator() {
    return creator;
  }

  public void setCreator(User creator) {
    this.creator = creator;
  }

  public ScheduledExport creatorId(Integer creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * Associated Creator ID
   * @return creatorId
  **/
  @ApiModelProperty(example = "null", value = "Associated Creator ID")
  public Integer getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(Integer creatorId) {
    this.creatorId = creatorId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledExport scheduledExport = (ScheduledExport) o;
    return Objects.equals(this.id, scheduledExport.id) &&
        Objects.equals(this.name, scheduledExport.name) &&
        Objects.equals(this.frequency, scheduledExport.frequency) &&
        Objects.equals(this.status, scheduledExport.status) &&
        Objects.equals(this.filter, scheduledExport.filter) &&
        Objects.equals(this.hour, scheduledExport.hour) &&
        Objects.equals(this.day, scheduledExport.day) &&
        Objects.equals(this.timeZone, scheduledExport.timeZone) &&
        Objects.equals(this.recipients, scheduledExport.recipients) &&
        Objects.equals(this.createdAt, scheduledExport.createdAt) &&
        Objects.equals(this.updatedAt, scheduledExport.updatedAt) &&
        Objects.equals(this.externalAccounts, scheduledExport.externalAccounts) &&
        Objects.equals(this.externalAccountIds, scheduledExport.externalAccountIds) &&
        Objects.equals(this.creator, scheduledExport.creator) &&
        Objects.equals(this.creatorId, scheduledExport.creatorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, frequency, status, filter, hour, day, timeZone, recipients, createdAt, updatedAt, externalAccounts, externalAccountIds, creator, creatorId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledExport {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    externalAccounts: ").append(toIndentedString(externalAccounts)).append("\n");
    sb.append("    externalAccountIds: ").append(toIndentedString(externalAccountIds)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

