/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * A(n) Service object
 */
@ApiModel(description = "A(n) Service object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class Service {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("default_interval")
  private Integer defaultInterval = null;

  @SerializedName("minimum_interval")
  private Integer minimumInterval = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("policy_name")
  private String policyName = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("provider")
  private String provider = null;

  public Service id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Service code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code associated with this service
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "The code associated with this service")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Service defaultInterval(Integer defaultInterval) {
    this.defaultInterval = defaultInterval;
    return this;
  }

   /**
   * Default interval used for scans if a scan interval was not created
   * @return defaultInterval
  **/
  @ApiModelProperty(example = "null", value = "Default interval used for scans if a scan interval was not created")
  public Integer getDefaultInterval() {
    return defaultInterval;
  }

  public void setDefaultInterval(Integer defaultInterval) {
    this.defaultInterval = defaultInterval;
  }

  public Service minimumInterval(Integer minimumInterval) {
    this.minimumInterval = minimumInterval;
    return this;
  }

   /**
   * Minimum interval allowed for scans on this service
   * @return minimumInterval
  **/
  @ApiModelProperty(example = "null", value = "Minimum interval allowed for scans on this service")
  public Integer getMinimumInterval() {
    return minimumInterval;
  }

  public void setMinimumInterval(Integer minimumInterval) {
    this.minimumInterval = minimumInterval;
  }

  public Service createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Service name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the service
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The name of the service")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Service policyName(String policyName) {
    this.policyName = policyName;
    return this;
  }

   /**
   * The policy name of the service. This matches the namespace set by Amazon
   * @return policyName
  **/
  @ApiModelProperty(example = "null", value = "The policy name of the service. This matches the namespace set by Amazon")
  public String getPolicyName() {
    return policyName;
  }

  public void setPolicyName(String policyName) {
    this.policyName = policyName;
  }

  public Service updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Service provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * The cloud provider this account is for
   * @return provider
  **/
  @ApiModelProperty(example = "null", value = "The cloud provider this account is for")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.id, service.id) &&
        Objects.equals(this.code, service.code) &&
        Objects.equals(this.defaultInterval, service.defaultInterval) &&
        Objects.equals(this.minimumInterval, service.minimumInterval) &&
        Objects.equals(this.createdAt, service.createdAt) &&
        Objects.equals(this.name, service.name) &&
        Objects.equals(this.policyName, service.policyName) &&
        Objects.equals(this.updatedAt, service.updatedAt) &&
        Objects.equals(this.provider, service.provider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, code, defaultInterval, minimumInterval, createdAt, name, policyName, updatedAt, provider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    defaultInterval: ").append(toIndentedString(defaultInterval)).append("\n");
    sb.append("    minimumInterval: ").append(toIndentedString(minimumInterval)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

