/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.Region;
import io.evident.models.Stat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A(n) StatRegion object
 */
@ApiModel(description = "A(n) StatRegion object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:00:36.864-05:00")
public class StatRegion {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("new_1h_high_pass")
  private Integer new1hHighPass = null;

  @SerializedName("new_1d_high_pass")
  private Integer new1dHighPass = null;

  @SerializedName("new_1w_high_pass")
  private Integer new1wHighPass = null;

  @SerializedName("old_high_pass")
  private Integer oldHighPass = null;

  @SerializedName("new_1h_high_fail")
  private Integer new1hHighFail = null;

  @SerializedName("new_1d_high_fail")
  private Integer new1dHighFail = null;

  @SerializedName("new_1w_high_fail")
  private Integer new1wHighFail = null;

  @SerializedName("old_high_fail")
  private Integer oldHighFail = null;

  @SerializedName("new_1h_high_warn")
  private Integer new1hHighWarn = null;

  @SerializedName("new_1d_high_warn")
  private Integer new1dHighWarn = null;

  @SerializedName("new_1w_high_warn")
  private Integer new1wHighWarn = null;

  @SerializedName("old_high_warn")
  private Integer oldHighWarn = null;

  @SerializedName("new_1h_high_error")
  private Integer new1hHighError = null;

  @SerializedName("new_1d_high_error")
  private Integer new1dHighError = null;

  @SerializedName("new_1w_high_error")
  private Integer new1wHighError = null;

  @SerializedName("old_high_error")
  private Integer oldHighError = null;

  @SerializedName("new_1h_medium_pass")
  private Integer new1hMediumPass = null;

  @SerializedName("new_1d_medium_pass")
  private Integer new1dMediumPass = null;

  @SerializedName("new_1w_medium_pass")
  private Integer new1wMediumPass = null;

  @SerializedName("old_medium_pass")
  private Integer oldMediumPass = null;

  @SerializedName("new_1h_medium_fail")
  private Integer new1hMediumFail = null;

  @SerializedName("new_1d_medium_fail")
  private Integer new1dMediumFail = null;

  @SerializedName("new_1w_medium_fail")
  private Integer new1wMediumFail = null;

  @SerializedName("old_medium_fail")
  private Integer oldMediumFail = null;

  @SerializedName("new_1h_medium_warn")
  private Integer new1hMediumWarn = null;

  @SerializedName("new_1d_medium_warn")
  private Integer new1dMediumWarn = null;

  @SerializedName("new_1w_medium_warn")
  private Integer new1wMediumWarn = null;

  @SerializedName("old_medium_warn")
  private Integer oldMediumWarn = null;

  @SerializedName("new_1h_medium_error")
  private Integer new1hMediumError = null;

  @SerializedName("new_1d_medium_error")
  private Integer new1dMediumError = null;

  @SerializedName("new_1w_medium_error")
  private Integer new1wMediumError = null;

  @SerializedName("old_medium_error")
  private Integer oldMediumError = null;

  @SerializedName("new_1h_low_pass")
  private Integer new1hLowPass = null;

  @SerializedName("new_1d_low_pass")
  private Integer new1dLowPass = null;

  @SerializedName("new_1w_low_pass")
  private Integer new1wLowPass = null;

  @SerializedName("old_low_pass")
  private Integer oldLowPass = null;

  @SerializedName("new_1h_low_fail")
  private Integer new1hLowFail = null;

  @SerializedName("new_1d_low_fail")
  private Integer new1dLowFail = null;

  @SerializedName("new_1w_low_fail")
  private Integer new1wLowFail = null;

  @SerializedName("old_low_fail")
  private Integer oldLowFail = null;

  @SerializedName("new_1h_low_warn")
  private Integer new1hLowWarn = null;

  @SerializedName("new_1d_low_warn")
  private Integer new1dLowWarn = null;

  @SerializedName("new_1w_low_warn")
  private Integer new1wLowWarn = null;

  @SerializedName("old_low_warn")
  private Integer oldLowWarn = null;

  @SerializedName("new_1h_low_error")
  private Integer new1hLowError = null;

  @SerializedName("new_1d_low_error")
  private Integer new1dLowError = null;

  @SerializedName("new_1w_low_error")
  private Integer new1wLowError = null;

  @SerializedName("old_low_error")
  private Integer oldLowError = null;

  @SerializedName("suppressed_high_pass")
  private Integer suppressedHighPass = null;

  @SerializedName("suppressed_high_fail")
  private Integer suppressedHighFail = null;

  @SerializedName("suppressed_high_warn")
  private Integer suppressedHighWarn = null;

  @SerializedName("suppressed_high_error")
  private Integer suppressedHighError = null;

  @SerializedName("suppressed_medium_pass")
  private Integer suppressedMediumPass = null;

  @SerializedName("suppressed_medium_fail")
  private Integer suppressedMediumFail = null;

  @SerializedName("suppressed_medium_warn")
  private Integer suppressedMediumWarn = null;

  @SerializedName("suppressed_medium_error")
  private Integer suppressedMediumError = null;

  @SerializedName("suppressed_low_pass")
  private Integer suppressedLowPass = null;

  @SerializedName("suppressed_low_fail")
  private Integer suppressedLowFail = null;

  @SerializedName("suppressed_low_warn")
  private Integer suppressedLowWarn = null;

  @SerializedName("suppressed_low_error")
  private Integer suppressedLowError = null;

  @SerializedName("new_1h_high_info")
  private Integer new1hHighInfo = null;

  @SerializedName("new_1d_high_info")
  private Integer new1dHighInfo = null;

  @SerializedName("new_1w_high_info")
  private Integer new1wHighInfo = null;

  @SerializedName("old_high_info")
  private Integer oldHighInfo = null;

  @SerializedName("new_1h_medium_info")
  private Integer new1hMediumInfo = null;

  @SerializedName("new_1d_medium_info")
  private Integer new1dMediumInfo = null;

  @SerializedName("new_1w_medium_info")
  private Integer new1wMediumInfo = null;

  @SerializedName("old_medium_info")
  private Integer oldMediumInfo = null;

  @SerializedName("new_1h_low_info")
  private Integer new1hLowInfo = null;

  @SerializedName("new_1d_low_info")
  private Integer new1dLowInfo = null;

  @SerializedName("new_1w_low_info")
  private Integer new1wLowInfo = null;

  @SerializedName("old_low_info")
  private Integer oldLowInfo = null;

  @SerializedName("suppressed_high_info")
  private Integer suppressedHighInfo = null;

  @SerializedName("suppressed_medium_info")
  private Integer suppressedMediumInfo = null;

  @SerializedName("suppressed_low_info")
  private Integer suppressedLowInfo = null;

  @SerializedName("region")
  private Region region = null;

  @SerializedName("region_id")
  private Integer regionId = null;

  @SerializedName("stat")
  private Stat stat = null;

  @SerializedName("stat_id")
  private Integer statId = null;

  public StatRegion id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public StatRegion new1hHighPass(Integer new1hHighPass) {
    this.new1hHighPass = new1hHighPass;
    return this;
  }

   /**
   * new_1h_high_pass
   * @return new1hHighPass
  **/
  @ApiModelProperty(example = "null", value = "new_1h_high_pass")
  public Integer getNew1hHighPass() {
    return new1hHighPass;
  }

  public void setNew1hHighPass(Integer new1hHighPass) {
    this.new1hHighPass = new1hHighPass;
  }

  public StatRegion new1dHighPass(Integer new1dHighPass) {
    this.new1dHighPass = new1dHighPass;
    return this;
  }

   /**
   * new_1d_high_pass
   * @return new1dHighPass
  **/
  @ApiModelProperty(example = "null", value = "new_1d_high_pass")
  public Integer getNew1dHighPass() {
    return new1dHighPass;
  }

  public void setNew1dHighPass(Integer new1dHighPass) {
    this.new1dHighPass = new1dHighPass;
  }

  public StatRegion new1wHighPass(Integer new1wHighPass) {
    this.new1wHighPass = new1wHighPass;
    return this;
  }

   /**
   * new_1w_high_pass
   * @return new1wHighPass
  **/
  @ApiModelProperty(example = "null", value = "new_1w_high_pass")
  public Integer getNew1wHighPass() {
    return new1wHighPass;
  }

  public void setNew1wHighPass(Integer new1wHighPass) {
    this.new1wHighPass = new1wHighPass;
  }

  public StatRegion oldHighPass(Integer oldHighPass) {
    this.oldHighPass = oldHighPass;
    return this;
  }

   /**
   * old_high_pass
   * @return oldHighPass
  **/
  @ApiModelProperty(example = "null", value = "old_high_pass")
  public Integer getOldHighPass() {
    return oldHighPass;
  }

  public void setOldHighPass(Integer oldHighPass) {
    this.oldHighPass = oldHighPass;
  }

  public StatRegion new1hHighFail(Integer new1hHighFail) {
    this.new1hHighFail = new1hHighFail;
    return this;
  }

   /**
   * new_1h_high_fail
   * @return new1hHighFail
  **/
  @ApiModelProperty(example = "null", value = "new_1h_high_fail")
  public Integer getNew1hHighFail() {
    return new1hHighFail;
  }

  public void setNew1hHighFail(Integer new1hHighFail) {
    this.new1hHighFail = new1hHighFail;
  }

  public StatRegion new1dHighFail(Integer new1dHighFail) {
    this.new1dHighFail = new1dHighFail;
    return this;
  }

   /**
   * new_1d_high_fail
   * @return new1dHighFail
  **/
  @ApiModelProperty(example = "null", value = "new_1d_high_fail")
  public Integer getNew1dHighFail() {
    return new1dHighFail;
  }

  public void setNew1dHighFail(Integer new1dHighFail) {
    this.new1dHighFail = new1dHighFail;
  }

  public StatRegion new1wHighFail(Integer new1wHighFail) {
    this.new1wHighFail = new1wHighFail;
    return this;
  }

   /**
   * new_1w_high_fail
   * @return new1wHighFail
  **/
  @ApiModelProperty(example = "null", value = "new_1w_high_fail")
  public Integer getNew1wHighFail() {
    return new1wHighFail;
  }

  public void setNew1wHighFail(Integer new1wHighFail) {
    this.new1wHighFail = new1wHighFail;
  }

  public StatRegion oldHighFail(Integer oldHighFail) {
    this.oldHighFail = oldHighFail;
    return this;
  }

   /**
   * old_high_fail
   * @return oldHighFail
  **/
  @ApiModelProperty(example = "null", value = "old_high_fail")
  public Integer getOldHighFail() {
    return oldHighFail;
  }

  public void setOldHighFail(Integer oldHighFail) {
    this.oldHighFail = oldHighFail;
  }

  public StatRegion new1hHighWarn(Integer new1hHighWarn) {
    this.new1hHighWarn = new1hHighWarn;
    return this;
  }

   /**
   * new_1h_high_warn
   * @return new1hHighWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1h_high_warn")
  public Integer getNew1hHighWarn() {
    return new1hHighWarn;
  }

  public void setNew1hHighWarn(Integer new1hHighWarn) {
    this.new1hHighWarn = new1hHighWarn;
  }

  public StatRegion new1dHighWarn(Integer new1dHighWarn) {
    this.new1dHighWarn = new1dHighWarn;
    return this;
  }

   /**
   * new_1d_high_warn
   * @return new1dHighWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1d_high_warn")
  public Integer getNew1dHighWarn() {
    return new1dHighWarn;
  }

  public void setNew1dHighWarn(Integer new1dHighWarn) {
    this.new1dHighWarn = new1dHighWarn;
  }

  public StatRegion new1wHighWarn(Integer new1wHighWarn) {
    this.new1wHighWarn = new1wHighWarn;
    return this;
  }

   /**
   * new_1w_high_warn
   * @return new1wHighWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1w_high_warn")
  public Integer getNew1wHighWarn() {
    return new1wHighWarn;
  }

  public void setNew1wHighWarn(Integer new1wHighWarn) {
    this.new1wHighWarn = new1wHighWarn;
  }

  public StatRegion oldHighWarn(Integer oldHighWarn) {
    this.oldHighWarn = oldHighWarn;
    return this;
  }

   /**
   * old_high_warn
   * @return oldHighWarn
  **/
  @ApiModelProperty(example = "null", value = "old_high_warn")
  public Integer getOldHighWarn() {
    return oldHighWarn;
  }

  public void setOldHighWarn(Integer oldHighWarn) {
    this.oldHighWarn = oldHighWarn;
  }

  public StatRegion new1hHighError(Integer new1hHighError) {
    this.new1hHighError = new1hHighError;
    return this;
  }

   /**
   * new_1h_high_error
   * @return new1hHighError
  **/
  @ApiModelProperty(example = "null", value = "new_1h_high_error")
  public Integer getNew1hHighError() {
    return new1hHighError;
  }

  public void setNew1hHighError(Integer new1hHighError) {
    this.new1hHighError = new1hHighError;
  }

  public StatRegion new1dHighError(Integer new1dHighError) {
    this.new1dHighError = new1dHighError;
    return this;
  }

   /**
   * new_1d_high_error
   * @return new1dHighError
  **/
  @ApiModelProperty(example = "null", value = "new_1d_high_error")
  public Integer getNew1dHighError() {
    return new1dHighError;
  }

  public void setNew1dHighError(Integer new1dHighError) {
    this.new1dHighError = new1dHighError;
  }

  public StatRegion new1wHighError(Integer new1wHighError) {
    this.new1wHighError = new1wHighError;
    return this;
  }

   /**
   * new_1w_high_error
   * @return new1wHighError
  **/
  @ApiModelProperty(example = "null", value = "new_1w_high_error")
  public Integer getNew1wHighError() {
    return new1wHighError;
  }

  public void setNew1wHighError(Integer new1wHighError) {
    this.new1wHighError = new1wHighError;
  }

  public StatRegion oldHighError(Integer oldHighError) {
    this.oldHighError = oldHighError;
    return this;
  }

   /**
   * old_high_error
   * @return oldHighError
  **/
  @ApiModelProperty(example = "null", value = "old_high_error")
  public Integer getOldHighError() {
    return oldHighError;
  }

  public void setOldHighError(Integer oldHighError) {
    this.oldHighError = oldHighError;
  }

  public StatRegion new1hMediumPass(Integer new1hMediumPass) {
    this.new1hMediumPass = new1hMediumPass;
    return this;
  }

   /**
   * new_1h_medium_pass
   * @return new1hMediumPass
  **/
  @ApiModelProperty(example = "null", value = "new_1h_medium_pass")
  public Integer getNew1hMediumPass() {
    return new1hMediumPass;
  }

  public void setNew1hMediumPass(Integer new1hMediumPass) {
    this.new1hMediumPass = new1hMediumPass;
  }

  public StatRegion new1dMediumPass(Integer new1dMediumPass) {
    this.new1dMediumPass = new1dMediumPass;
    return this;
  }

   /**
   * new_1d_medium_pass
   * @return new1dMediumPass
  **/
  @ApiModelProperty(example = "null", value = "new_1d_medium_pass")
  public Integer getNew1dMediumPass() {
    return new1dMediumPass;
  }

  public void setNew1dMediumPass(Integer new1dMediumPass) {
    this.new1dMediumPass = new1dMediumPass;
  }

  public StatRegion new1wMediumPass(Integer new1wMediumPass) {
    this.new1wMediumPass = new1wMediumPass;
    return this;
  }

   /**
   * new_1w_medium_pass
   * @return new1wMediumPass
  **/
  @ApiModelProperty(example = "null", value = "new_1w_medium_pass")
  public Integer getNew1wMediumPass() {
    return new1wMediumPass;
  }

  public void setNew1wMediumPass(Integer new1wMediumPass) {
    this.new1wMediumPass = new1wMediumPass;
  }

  public StatRegion oldMediumPass(Integer oldMediumPass) {
    this.oldMediumPass = oldMediumPass;
    return this;
  }

   /**
   * old_medium_pass
   * @return oldMediumPass
  **/
  @ApiModelProperty(example = "null", value = "old_medium_pass")
  public Integer getOldMediumPass() {
    return oldMediumPass;
  }

  public void setOldMediumPass(Integer oldMediumPass) {
    this.oldMediumPass = oldMediumPass;
  }

  public StatRegion new1hMediumFail(Integer new1hMediumFail) {
    this.new1hMediumFail = new1hMediumFail;
    return this;
  }

   /**
   * new_1h_medium_fail
   * @return new1hMediumFail
  **/
  @ApiModelProperty(example = "null", value = "new_1h_medium_fail")
  public Integer getNew1hMediumFail() {
    return new1hMediumFail;
  }

  public void setNew1hMediumFail(Integer new1hMediumFail) {
    this.new1hMediumFail = new1hMediumFail;
  }

  public StatRegion new1dMediumFail(Integer new1dMediumFail) {
    this.new1dMediumFail = new1dMediumFail;
    return this;
  }

   /**
   * new_1d_medium_fail
   * @return new1dMediumFail
  **/
  @ApiModelProperty(example = "null", value = "new_1d_medium_fail")
  public Integer getNew1dMediumFail() {
    return new1dMediumFail;
  }

  public void setNew1dMediumFail(Integer new1dMediumFail) {
    this.new1dMediumFail = new1dMediumFail;
  }

  public StatRegion new1wMediumFail(Integer new1wMediumFail) {
    this.new1wMediumFail = new1wMediumFail;
    return this;
  }

   /**
   * new_1w_medium_fail
   * @return new1wMediumFail
  **/
  @ApiModelProperty(example = "null", value = "new_1w_medium_fail")
  public Integer getNew1wMediumFail() {
    return new1wMediumFail;
  }

  public void setNew1wMediumFail(Integer new1wMediumFail) {
    this.new1wMediumFail = new1wMediumFail;
  }

  public StatRegion oldMediumFail(Integer oldMediumFail) {
    this.oldMediumFail = oldMediumFail;
    return this;
  }

   /**
   * old_medium_fail
   * @return oldMediumFail
  **/
  @ApiModelProperty(example = "null", value = "old_medium_fail")
  public Integer getOldMediumFail() {
    return oldMediumFail;
  }

  public void setOldMediumFail(Integer oldMediumFail) {
    this.oldMediumFail = oldMediumFail;
  }

  public StatRegion new1hMediumWarn(Integer new1hMediumWarn) {
    this.new1hMediumWarn = new1hMediumWarn;
    return this;
  }

   /**
   * new_1h_medium_warn
   * @return new1hMediumWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1h_medium_warn")
  public Integer getNew1hMediumWarn() {
    return new1hMediumWarn;
  }

  public void setNew1hMediumWarn(Integer new1hMediumWarn) {
    this.new1hMediumWarn = new1hMediumWarn;
  }

  public StatRegion new1dMediumWarn(Integer new1dMediumWarn) {
    this.new1dMediumWarn = new1dMediumWarn;
    return this;
  }

   /**
   * new_1d_medium_warn
   * @return new1dMediumWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1d_medium_warn")
  public Integer getNew1dMediumWarn() {
    return new1dMediumWarn;
  }

  public void setNew1dMediumWarn(Integer new1dMediumWarn) {
    this.new1dMediumWarn = new1dMediumWarn;
  }

  public StatRegion new1wMediumWarn(Integer new1wMediumWarn) {
    this.new1wMediumWarn = new1wMediumWarn;
    return this;
  }

   /**
   * new_1w_medium_warn
   * @return new1wMediumWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1w_medium_warn")
  public Integer getNew1wMediumWarn() {
    return new1wMediumWarn;
  }

  public void setNew1wMediumWarn(Integer new1wMediumWarn) {
    this.new1wMediumWarn = new1wMediumWarn;
  }

  public StatRegion oldMediumWarn(Integer oldMediumWarn) {
    this.oldMediumWarn = oldMediumWarn;
    return this;
  }

   /**
   * old_medium_warn
   * @return oldMediumWarn
  **/
  @ApiModelProperty(example = "null", value = "old_medium_warn")
  public Integer getOldMediumWarn() {
    return oldMediumWarn;
  }

  public void setOldMediumWarn(Integer oldMediumWarn) {
    this.oldMediumWarn = oldMediumWarn;
  }

  public StatRegion new1hMediumError(Integer new1hMediumError) {
    this.new1hMediumError = new1hMediumError;
    return this;
  }

   /**
   * new_1h_medium_error
   * @return new1hMediumError
  **/
  @ApiModelProperty(example = "null", value = "new_1h_medium_error")
  public Integer getNew1hMediumError() {
    return new1hMediumError;
  }

  public void setNew1hMediumError(Integer new1hMediumError) {
    this.new1hMediumError = new1hMediumError;
  }

  public StatRegion new1dMediumError(Integer new1dMediumError) {
    this.new1dMediumError = new1dMediumError;
    return this;
  }

   /**
   * new_1d_medium_error
   * @return new1dMediumError
  **/
  @ApiModelProperty(example = "null", value = "new_1d_medium_error")
  public Integer getNew1dMediumError() {
    return new1dMediumError;
  }

  public void setNew1dMediumError(Integer new1dMediumError) {
    this.new1dMediumError = new1dMediumError;
  }

  public StatRegion new1wMediumError(Integer new1wMediumError) {
    this.new1wMediumError = new1wMediumError;
    return this;
  }

   /**
   * new_1w_medium_error
   * @return new1wMediumError
  **/
  @ApiModelProperty(example = "null", value = "new_1w_medium_error")
  public Integer getNew1wMediumError() {
    return new1wMediumError;
  }

  public void setNew1wMediumError(Integer new1wMediumError) {
    this.new1wMediumError = new1wMediumError;
  }

  public StatRegion oldMediumError(Integer oldMediumError) {
    this.oldMediumError = oldMediumError;
    return this;
  }

   /**
   * old_medium_error
   * @return oldMediumError
  **/
  @ApiModelProperty(example = "null", value = "old_medium_error")
  public Integer getOldMediumError() {
    return oldMediumError;
  }

  public void setOldMediumError(Integer oldMediumError) {
    this.oldMediumError = oldMediumError;
  }

  public StatRegion new1hLowPass(Integer new1hLowPass) {
    this.new1hLowPass = new1hLowPass;
    return this;
  }

   /**
   * new_1h_low_pass
   * @return new1hLowPass
  **/
  @ApiModelProperty(example = "null", value = "new_1h_low_pass")
  public Integer getNew1hLowPass() {
    return new1hLowPass;
  }

  public void setNew1hLowPass(Integer new1hLowPass) {
    this.new1hLowPass = new1hLowPass;
  }

  public StatRegion new1dLowPass(Integer new1dLowPass) {
    this.new1dLowPass = new1dLowPass;
    return this;
  }

   /**
   * new_1d_low_pass
   * @return new1dLowPass
  **/
  @ApiModelProperty(example = "null", value = "new_1d_low_pass")
  public Integer getNew1dLowPass() {
    return new1dLowPass;
  }

  public void setNew1dLowPass(Integer new1dLowPass) {
    this.new1dLowPass = new1dLowPass;
  }

  public StatRegion new1wLowPass(Integer new1wLowPass) {
    this.new1wLowPass = new1wLowPass;
    return this;
  }

   /**
   * new_1w_low_pass
   * @return new1wLowPass
  **/
  @ApiModelProperty(example = "null", value = "new_1w_low_pass")
  public Integer getNew1wLowPass() {
    return new1wLowPass;
  }

  public void setNew1wLowPass(Integer new1wLowPass) {
    this.new1wLowPass = new1wLowPass;
  }

  public StatRegion oldLowPass(Integer oldLowPass) {
    this.oldLowPass = oldLowPass;
    return this;
  }

   /**
   * old_low_pass
   * @return oldLowPass
  **/
  @ApiModelProperty(example = "null", value = "old_low_pass")
  public Integer getOldLowPass() {
    return oldLowPass;
  }

  public void setOldLowPass(Integer oldLowPass) {
    this.oldLowPass = oldLowPass;
  }

  public StatRegion new1hLowFail(Integer new1hLowFail) {
    this.new1hLowFail = new1hLowFail;
    return this;
  }

   /**
   * new_1h_low_fail
   * @return new1hLowFail
  **/
  @ApiModelProperty(example = "null", value = "new_1h_low_fail")
  public Integer getNew1hLowFail() {
    return new1hLowFail;
  }

  public void setNew1hLowFail(Integer new1hLowFail) {
    this.new1hLowFail = new1hLowFail;
  }

  public StatRegion new1dLowFail(Integer new1dLowFail) {
    this.new1dLowFail = new1dLowFail;
    return this;
  }

   /**
   * new_1d_low_fail
   * @return new1dLowFail
  **/
  @ApiModelProperty(example = "null", value = "new_1d_low_fail")
  public Integer getNew1dLowFail() {
    return new1dLowFail;
  }

  public void setNew1dLowFail(Integer new1dLowFail) {
    this.new1dLowFail = new1dLowFail;
  }

  public StatRegion new1wLowFail(Integer new1wLowFail) {
    this.new1wLowFail = new1wLowFail;
    return this;
  }

   /**
   * new_1w_low_fail
   * @return new1wLowFail
  **/
  @ApiModelProperty(example = "null", value = "new_1w_low_fail")
  public Integer getNew1wLowFail() {
    return new1wLowFail;
  }

  public void setNew1wLowFail(Integer new1wLowFail) {
    this.new1wLowFail = new1wLowFail;
  }

  public StatRegion oldLowFail(Integer oldLowFail) {
    this.oldLowFail = oldLowFail;
    return this;
  }

   /**
   * old_low_fail
   * @return oldLowFail
  **/
  @ApiModelProperty(example = "null", value = "old_low_fail")
  public Integer getOldLowFail() {
    return oldLowFail;
  }

  public void setOldLowFail(Integer oldLowFail) {
    this.oldLowFail = oldLowFail;
  }

  public StatRegion new1hLowWarn(Integer new1hLowWarn) {
    this.new1hLowWarn = new1hLowWarn;
    return this;
  }

   /**
   * new_1h_low_warn
   * @return new1hLowWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1h_low_warn")
  public Integer getNew1hLowWarn() {
    return new1hLowWarn;
  }

  public void setNew1hLowWarn(Integer new1hLowWarn) {
    this.new1hLowWarn = new1hLowWarn;
  }

  public StatRegion new1dLowWarn(Integer new1dLowWarn) {
    this.new1dLowWarn = new1dLowWarn;
    return this;
  }

   /**
   * new_1d_low_warn
   * @return new1dLowWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1d_low_warn")
  public Integer getNew1dLowWarn() {
    return new1dLowWarn;
  }

  public void setNew1dLowWarn(Integer new1dLowWarn) {
    this.new1dLowWarn = new1dLowWarn;
  }

  public StatRegion new1wLowWarn(Integer new1wLowWarn) {
    this.new1wLowWarn = new1wLowWarn;
    return this;
  }

   /**
   * new_1w_low_warn
   * @return new1wLowWarn
  **/
  @ApiModelProperty(example = "null", value = "new_1w_low_warn")
  public Integer getNew1wLowWarn() {
    return new1wLowWarn;
  }

  public void setNew1wLowWarn(Integer new1wLowWarn) {
    this.new1wLowWarn = new1wLowWarn;
  }

  public StatRegion oldLowWarn(Integer oldLowWarn) {
    this.oldLowWarn = oldLowWarn;
    return this;
  }

   /**
   * old_low_warn
   * @return oldLowWarn
  **/
  @ApiModelProperty(example = "null", value = "old_low_warn")
  public Integer getOldLowWarn() {
    return oldLowWarn;
  }

  public void setOldLowWarn(Integer oldLowWarn) {
    this.oldLowWarn = oldLowWarn;
  }

  public StatRegion new1hLowError(Integer new1hLowError) {
    this.new1hLowError = new1hLowError;
    return this;
  }

   /**
   * new_1h_low_error
   * @return new1hLowError
  **/
  @ApiModelProperty(example = "null", value = "new_1h_low_error")
  public Integer getNew1hLowError() {
    return new1hLowError;
  }

  public void setNew1hLowError(Integer new1hLowError) {
    this.new1hLowError = new1hLowError;
  }

  public StatRegion new1dLowError(Integer new1dLowError) {
    this.new1dLowError = new1dLowError;
    return this;
  }

   /**
   * new_1d_low_error
   * @return new1dLowError
  **/
  @ApiModelProperty(example = "null", value = "new_1d_low_error")
  public Integer getNew1dLowError() {
    return new1dLowError;
  }

  public void setNew1dLowError(Integer new1dLowError) {
    this.new1dLowError = new1dLowError;
  }

  public StatRegion new1wLowError(Integer new1wLowError) {
    this.new1wLowError = new1wLowError;
    return this;
  }

   /**
   * new_1w_low_error
   * @return new1wLowError
  **/
  @ApiModelProperty(example = "null", value = "new_1w_low_error")
  public Integer getNew1wLowError() {
    return new1wLowError;
  }

  public void setNew1wLowError(Integer new1wLowError) {
    this.new1wLowError = new1wLowError;
  }

  public StatRegion oldLowError(Integer oldLowError) {
    this.oldLowError = oldLowError;
    return this;
  }

   /**
   * old_low_error
   * @return oldLowError
  **/
  @ApiModelProperty(example = "null", value = "old_low_error")
  public Integer getOldLowError() {
    return oldLowError;
  }

  public void setOldLowError(Integer oldLowError) {
    this.oldLowError = oldLowError;
  }

  public StatRegion suppressedHighPass(Integer suppressedHighPass) {
    this.suppressedHighPass = suppressedHighPass;
    return this;
  }

   /**
   * suppressed_high_pass
   * @return suppressedHighPass
  **/
  @ApiModelProperty(example = "null", value = "suppressed_high_pass")
  public Integer getSuppressedHighPass() {
    return suppressedHighPass;
  }

  public void setSuppressedHighPass(Integer suppressedHighPass) {
    this.suppressedHighPass = suppressedHighPass;
  }

  public StatRegion suppressedHighFail(Integer suppressedHighFail) {
    this.suppressedHighFail = suppressedHighFail;
    return this;
  }

   /**
   * suppressed_high_fail
   * @return suppressedHighFail
  **/
  @ApiModelProperty(example = "null", value = "suppressed_high_fail")
  public Integer getSuppressedHighFail() {
    return suppressedHighFail;
  }

  public void setSuppressedHighFail(Integer suppressedHighFail) {
    this.suppressedHighFail = suppressedHighFail;
  }

  public StatRegion suppressedHighWarn(Integer suppressedHighWarn) {
    this.suppressedHighWarn = suppressedHighWarn;
    return this;
  }

   /**
   * suppressed_high_warn
   * @return suppressedHighWarn
  **/
  @ApiModelProperty(example = "null", value = "suppressed_high_warn")
  public Integer getSuppressedHighWarn() {
    return suppressedHighWarn;
  }

  public void setSuppressedHighWarn(Integer suppressedHighWarn) {
    this.suppressedHighWarn = suppressedHighWarn;
  }

  public StatRegion suppressedHighError(Integer suppressedHighError) {
    this.suppressedHighError = suppressedHighError;
    return this;
  }

   /**
   * suppressed_high_error
   * @return suppressedHighError
  **/
  @ApiModelProperty(example = "null", value = "suppressed_high_error")
  public Integer getSuppressedHighError() {
    return suppressedHighError;
  }

  public void setSuppressedHighError(Integer suppressedHighError) {
    this.suppressedHighError = suppressedHighError;
  }

  public StatRegion suppressedMediumPass(Integer suppressedMediumPass) {
    this.suppressedMediumPass = suppressedMediumPass;
    return this;
  }

   /**
   * suppressed_medium_pass
   * @return suppressedMediumPass
  **/
  @ApiModelProperty(example = "null", value = "suppressed_medium_pass")
  public Integer getSuppressedMediumPass() {
    return suppressedMediumPass;
  }

  public void setSuppressedMediumPass(Integer suppressedMediumPass) {
    this.suppressedMediumPass = suppressedMediumPass;
  }

  public StatRegion suppressedMediumFail(Integer suppressedMediumFail) {
    this.suppressedMediumFail = suppressedMediumFail;
    return this;
  }

   /**
   * suppressed_medium_fail
   * @return suppressedMediumFail
  **/
  @ApiModelProperty(example = "null", value = "suppressed_medium_fail")
  public Integer getSuppressedMediumFail() {
    return suppressedMediumFail;
  }

  public void setSuppressedMediumFail(Integer suppressedMediumFail) {
    this.suppressedMediumFail = suppressedMediumFail;
  }

  public StatRegion suppressedMediumWarn(Integer suppressedMediumWarn) {
    this.suppressedMediumWarn = suppressedMediumWarn;
    return this;
  }

   /**
   * suppressed_medium_warn
   * @return suppressedMediumWarn
  **/
  @ApiModelProperty(example = "null", value = "suppressed_medium_warn")
  public Integer getSuppressedMediumWarn() {
    return suppressedMediumWarn;
  }

  public void setSuppressedMediumWarn(Integer suppressedMediumWarn) {
    this.suppressedMediumWarn = suppressedMediumWarn;
  }

  public StatRegion suppressedMediumError(Integer suppressedMediumError) {
    this.suppressedMediumError = suppressedMediumError;
    return this;
  }

   /**
   * suppressed_medium_error
   * @return suppressedMediumError
  **/
  @ApiModelProperty(example = "null", value = "suppressed_medium_error")
  public Integer getSuppressedMediumError() {
    return suppressedMediumError;
  }

  public void setSuppressedMediumError(Integer suppressedMediumError) {
    this.suppressedMediumError = suppressedMediumError;
  }

  public StatRegion suppressedLowPass(Integer suppressedLowPass) {
    this.suppressedLowPass = suppressedLowPass;
    return this;
  }

   /**
   * suppressed_low_pass
   * @return suppressedLowPass
  **/
  @ApiModelProperty(example = "null", value = "suppressed_low_pass")
  public Integer getSuppressedLowPass() {
    return suppressedLowPass;
  }

  public void setSuppressedLowPass(Integer suppressedLowPass) {
    this.suppressedLowPass = suppressedLowPass;
  }

  public StatRegion suppressedLowFail(Integer suppressedLowFail) {
    this.suppressedLowFail = suppressedLowFail;
    return this;
  }

   /**
   * suppressed_low_fail
   * @return suppressedLowFail
  **/
  @ApiModelProperty(example = "null", value = "suppressed_low_fail")
  public Integer getSuppressedLowFail() {
    return suppressedLowFail;
  }

  public void setSuppressedLowFail(Integer suppressedLowFail) {
    this.suppressedLowFail = suppressedLowFail;
  }

  public StatRegion suppressedLowWarn(Integer suppressedLowWarn) {
    this.suppressedLowWarn = suppressedLowWarn;
    return this;
  }

   /**
   * suppressed_low_warn
   * @return suppressedLowWarn
  **/
  @ApiModelProperty(example = "null", value = "suppressed_low_warn")
  public Integer getSuppressedLowWarn() {
    return suppressedLowWarn;
  }

  public void setSuppressedLowWarn(Integer suppressedLowWarn) {
    this.suppressedLowWarn = suppressedLowWarn;
  }

  public StatRegion suppressedLowError(Integer suppressedLowError) {
    this.suppressedLowError = suppressedLowError;
    return this;
  }

   /**
   * suppressed_low_error
   * @return suppressedLowError
  **/
  @ApiModelProperty(example = "null", value = "suppressed_low_error")
  public Integer getSuppressedLowError() {
    return suppressedLowError;
  }

  public void setSuppressedLowError(Integer suppressedLowError) {
    this.suppressedLowError = suppressedLowError;
  }

  public StatRegion new1hHighInfo(Integer new1hHighInfo) {
    this.new1hHighInfo = new1hHighInfo;
    return this;
  }

   /**
   * new_1h_high_info
   * @return new1hHighInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1h_high_info")
  public Integer getNew1hHighInfo() {
    return new1hHighInfo;
  }

  public void setNew1hHighInfo(Integer new1hHighInfo) {
    this.new1hHighInfo = new1hHighInfo;
  }

  public StatRegion new1dHighInfo(Integer new1dHighInfo) {
    this.new1dHighInfo = new1dHighInfo;
    return this;
  }

   /**
   * new_1d_high_info
   * @return new1dHighInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1d_high_info")
  public Integer getNew1dHighInfo() {
    return new1dHighInfo;
  }

  public void setNew1dHighInfo(Integer new1dHighInfo) {
    this.new1dHighInfo = new1dHighInfo;
  }

  public StatRegion new1wHighInfo(Integer new1wHighInfo) {
    this.new1wHighInfo = new1wHighInfo;
    return this;
  }

   /**
   * new_1w_high_info
   * @return new1wHighInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1w_high_info")
  public Integer getNew1wHighInfo() {
    return new1wHighInfo;
  }

  public void setNew1wHighInfo(Integer new1wHighInfo) {
    this.new1wHighInfo = new1wHighInfo;
  }

  public StatRegion oldHighInfo(Integer oldHighInfo) {
    this.oldHighInfo = oldHighInfo;
    return this;
  }

   /**
   * old_high_info
   * @return oldHighInfo
  **/
  @ApiModelProperty(example = "null", value = "old_high_info")
  public Integer getOldHighInfo() {
    return oldHighInfo;
  }

  public void setOldHighInfo(Integer oldHighInfo) {
    this.oldHighInfo = oldHighInfo;
  }

  public StatRegion new1hMediumInfo(Integer new1hMediumInfo) {
    this.new1hMediumInfo = new1hMediumInfo;
    return this;
  }

   /**
   * new_1h_medium_info
   * @return new1hMediumInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1h_medium_info")
  public Integer getNew1hMediumInfo() {
    return new1hMediumInfo;
  }

  public void setNew1hMediumInfo(Integer new1hMediumInfo) {
    this.new1hMediumInfo = new1hMediumInfo;
  }

  public StatRegion new1dMediumInfo(Integer new1dMediumInfo) {
    this.new1dMediumInfo = new1dMediumInfo;
    return this;
  }

   /**
   * new_1d_medium_info
   * @return new1dMediumInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1d_medium_info")
  public Integer getNew1dMediumInfo() {
    return new1dMediumInfo;
  }

  public void setNew1dMediumInfo(Integer new1dMediumInfo) {
    this.new1dMediumInfo = new1dMediumInfo;
  }

  public StatRegion new1wMediumInfo(Integer new1wMediumInfo) {
    this.new1wMediumInfo = new1wMediumInfo;
    return this;
  }

   /**
   * new_1w_medium_info
   * @return new1wMediumInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1w_medium_info")
  public Integer getNew1wMediumInfo() {
    return new1wMediumInfo;
  }

  public void setNew1wMediumInfo(Integer new1wMediumInfo) {
    this.new1wMediumInfo = new1wMediumInfo;
  }

  public StatRegion oldMediumInfo(Integer oldMediumInfo) {
    this.oldMediumInfo = oldMediumInfo;
    return this;
  }

   /**
   * old_medium_info
   * @return oldMediumInfo
  **/
  @ApiModelProperty(example = "null", value = "old_medium_info")
  public Integer getOldMediumInfo() {
    return oldMediumInfo;
  }

  public void setOldMediumInfo(Integer oldMediumInfo) {
    this.oldMediumInfo = oldMediumInfo;
  }

  public StatRegion new1hLowInfo(Integer new1hLowInfo) {
    this.new1hLowInfo = new1hLowInfo;
    return this;
  }

   /**
   * new_1h_low_info
   * @return new1hLowInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1h_low_info")
  public Integer getNew1hLowInfo() {
    return new1hLowInfo;
  }

  public void setNew1hLowInfo(Integer new1hLowInfo) {
    this.new1hLowInfo = new1hLowInfo;
  }

  public StatRegion new1dLowInfo(Integer new1dLowInfo) {
    this.new1dLowInfo = new1dLowInfo;
    return this;
  }

   /**
   * new_1d_low_info
   * @return new1dLowInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1d_low_info")
  public Integer getNew1dLowInfo() {
    return new1dLowInfo;
  }

  public void setNew1dLowInfo(Integer new1dLowInfo) {
    this.new1dLowInfo = new1dLowInfo;
  }

  public StatRegion new1wLowInfo(Integer new1wLowInfo) {
    this.new1wLowInfo = new1wLowInfo;
    return this;
  }

   /**
   * new_1w_low_info
   * @return new1wLowInfo
  **/
  @ApiModelProperty(example = "null", value = "new_1w_low_info")
  public Integer getNew1wLowInfo() {
    return new1wLowInfo;
  }

  public void setNew1wLowInfo(Integer new1wLowInfo) {
    this.new1wLowInfo = new1wLowInfo;
  }

  public StatRegion oldLowInfo(Integer oldLowInfo) {
    this.oldLowInfo = oldLowInfo;
    return this;
  }

   /**
   * old_low_info
   * @return oldLowInfo
  **/
  @ApiModelProperty(example = "null", value = "old_low_info")
  public Integer getOldLowInfo() {
    return oldLowInfo;
  }

  public void setOldLowInfo(Integer oldLowInfo) {
    this.oldLowInfo = oldLowInfo;
  }

  public StatRegion suppressedHighInfo(Integer suppressedHighInfo) {
    this.suppressedHighInfo = suppressedHighInfo;
    return this;
  }

   /**
   * suppressed_high_info
   * @return suppressedHighInfo
  **/
  @ApiModelProperty(example = "null", value = "suppressed_high_info")
  public Integer getSuppressedHighInfo() {
    return suppressedHighInfo;
  }

  public void setSuppressedHighInfo(Integer suppressedHighInfo) {
    this.suppressedHighInfo = suppressedHighInfo;
  }

  public StatRegion suppressedMediumInfo(Integer suppressedMediumInfo) {
    this.suppressedMediumInfo = suppressedMediumInfo;
    return this;
  }

   /**
   * suppressed_medium_info
   * @return suppressedMediumInfo
  **/
  @ApiModelProperty(example = "null", value = "suppressed_medium_info")
  public Integer getSuppressedMediumInfo() {
    return suppressedMediumInfo;
  }

  public void setSuppressedMediumInfo(Integer suppressedMediumInfo) {
    this.suppressedMediumInfo = suppressedMediumInfo;
  }

  public StatRegion suppressedLowInfo(Integer suppressedLowInfo) {
    this.suppressedLowInfo = suppressedLowInfo;
    return this;
  }

   /**
   * suppressed_low_info
   * @return suppressedLowInfo
  **/
  @ApiModelProperty(example = "null", value = "suppressed_low_info")
  public Integer getSuppressedLowInfo() {
    return suppressedLowInfo;
  }

  public void setSuppressedLowInfo(Integer suppressedLowInfo) {
    this.suppressedLowInfo = suppressedLowInfo;
  }

  public StatRegion region(Region region) {
    this.region = region;
    return this;
  }

   /**
   * Associated Region
   * @return region
  **/
  @ApiModelProperty(example = "null", value = "Associated Region")
  public Region getRegion() {
    return region;
  }

  public void setRegion(Region region) {
    this.region = region;
  }

  public StatRegion regionId(Integer regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Associated Region ID
   * @return regionId
  **/
  @ApiModelProperty(example = "null", value = "Associated Region ID")
  public Integer getRegionId() {
    return regionId;
  }

  public void setRegionId(Integer regionId) {
    this.regionId = regionId;
  }

  public StatRegion stat(Stat stat) {
    this.stat = stat;
    return this;
  }

   /**
   * Associated Stat
   * @return stat
  **/
  @ApiModelProperty(example = "null", value = "Associated Stat")
  public Stat getStat() {
    return stat;
  }

  public void setStat(Stat stat) {
    this.stat = stat;
  }

  public StatRegion statId(Integer statId) {
    this.statId = statId;
    return this;
  }

   /**
   * Associated Stat ID
   * @return statId
  **/
  @ApiModelProperty(example = "null", value = "Associated Stat ID")
  public Integer getStatId() {
    return statId;
  }

  public void setStatId(Integer statId) {
    this.statId = statId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatRegion statRegion = (StatRegion) o;
    return Objects.equals(this.id, statRegion.id) &&
        Objects.equals(this.new1hHighPass, statRegion.new1hHighPass) &&
        Objects.equals(this.new1dHighPass, statRegion.new1dHighPass) &&
        Objects.equals(this.new1wHighPass, statRegion.new1wHighPass) &&
        Objects.equals(this.oldHighPass, statRegion.oldHighPass) &&
        Objects.equals(this.new1hHighFail, statRegion.new1hHighFail) &&
        Objects.equals(this.new1dHighFail, statRegion.new1dHighFail) &&
        Objects.equals(this.new1wHighFail, statRegion.new1wHighFail) &&
        Objects.equals(this.oldHighFail, statRegion.oldHighFail) &&
        Objects.equals(this.new1hHighWarn, statRegion.new1hHighWarn) &&
        Objects.equals(this.new1dHighWarn, statRegion.new1dHighWarn) &&
        Objects.equals(this.new1wHighWarn, statRegion.new1wHighWarn) &&
        Objects.equals(this.oldHighWarn, statRegion.oldHighWarn) &&
        Objects.equals(this.new1hHighError, statRegion.new1hHighError) &&
        Objects.equals(this.new1dHighError, statRegion.new1dHighError) &&
        Objects.equals(this.new1wHighError, statRegion.new1wHighError) &&
        Objects.equals(this.oldHighError, statRegion.oldHighError) &&
        Objects.equals(this.new1hMediumPass, statRegion.new1hMediumPass) &&
        Objects.equals(this.new1dMediumPass, statRegion.new1dMediumPass) &&
        Objects.equals(this.new1wMediumPass, statRegion.new1wMediumPass) &&
        Objects.equals(this.oldMediumPass, statRegion.oldMediumPass) &&
        Objects.equals(this.new1hMediumFail, statRegion.new1hMediumFail) &&
        Objects.equals(this.new1dMediumFail, statRegion.new1dMediumFail) &&
        Objects.equals(this.new1wMediumFail, statRegion.new1wMediumFail) &&
        Objects.equals(this.oldMediumFail, statRegion.oldMediumFail) &&
        Objects.equals(this.new1hMediumWarn, statRegion.new1hMediumWarn) &&
        Objects.equals(this.new1dMediumWarn, statRegion.new1dMediumWarn) &&
        Objects.equals(this.new1wMediumWarn, statRegion.new1wMediumWarn) &&
        Objects.equals(this.oldMediumWarn, statRegion.oldMediumWarn) &&
        Objects.equals(this.new1hMediumError, statRegion.new1hMediumError) &&
        Objects.equals(this.new1dMediumError, statRegion.new1dMediumError) &&
        Objects.equals(this.new1wMediumError, statRegion.new1wMediumError) &&
        Objects.equals(this.oldMediumError, statRegion.oldMediumError) &&
        Objects.equals(this.new1hLowPass, statRegion.new1hLowPass) &&
        Objects.equals(this.new1dLowPass, statRegion.new1dLowPass) &&
        Objects.equals(this.new1wLowPass, statRegion.new1wLowPass) &&
        Objects.equals(this.oldLowPass, statRegion.oldLowPass) &&
        Objects.equals(this.new1hLowFail, statRegion.new1hLowFail) &&
        Objects.equals(this.new1dLowFail, statRegion.new1dLowFail) &&
        Objects.equals(this.new1wLowFail, statRegion.new1wLowFail) &&
        Objects.equals(this.oldLowFail, statRegion.oldLowFail) &&
        Objects.equals(this.new1hLowWarn, statRegion.new1hLowWarn) &&
        Objects.equals(this.new1dLowWarn, statRegion.new1dLowWarn) &&
        Objects.equals(this.new1wLowWarn, statRegion.new1wLowWarn) &&
        Objects.equals(this.oldLowWarn, statRegion.oldLowWarn) &&
        Objects.equals(this.new1hLowError, statRegion.new1hLowError) &&
        Objects.equals(this.new1dLowError, statRegion.new1dLowError) &&
        Objects.equals(this.new1wLowError, statRegion.new1wLowError) &&
        Objects.equals(this.oldLowError, statRegion.oldLowError) &&
        Objects.equals(this.suppressedHighPass, statRegion.suppressedHighPass) &&
        Objects.equals(this.suppressedHighFail, statRegion.suppressedHighFail) &&
        Objects.equals(this.suppressedHighWarn, statRegion.suppressedHighWarn) &&
        Objects.equals(this.suppressedHighError, statRegion.suppressedHighError) &&
        Objects.equals(this.suppressedMediumPass, statRegion.suppressedMediumPass) &&
        Objects.equals(this.suppressedMediumFail, statRegion.suppressedMediumFail) &&
        Objects.equals(this.suppressedMediumWarn, statRegion.suppressedMediumWarn) &&
        Objects.equals(this.suppressedMediumError, statRegion.suppressedMediumError) &&
        Objects.equals(this.suppressedLowPass, statRegion.suppressedLowPass) &&
        Objects.equals(this.suppressedLowFail, statRegion.suppressedLowFail) &&
        Objects.equals(this.suppressedLowWarn, statRegion.suppressedLowWarn) &&
        Objects.equals(this.suppressedLowError, statRegion.suppressedLowError) &&
        Objects.equals(this.new1hHighInfo, statRegion.new1hHighInfo) &&
        Objects.equals(this.new1dHighInfo, statRegion.new1dHighInfo) &&
        Objects.equals(this.new1wHighInfo, statRegion.new1wHighInfo) &&
        Objects.equals(this.oldHighInfo, statRegion.oldHighInfo) &&
        Objects.equals(this.new1hMediumInfo, statRegion.new1hMediumInfo) &&
        Objects.equals(this.new1dMediumInfo, statRegion.new1dMediumInfo) &&
        Objects.equals(this.new1wMediumInfo, statRegion.new1wMediumInfo) &&
        Objects.equals(this.oldMediumInfo, statRegion.oldMediumInfo) &&
        Objects.equals(this.new1hLowInfo, statRegion.new1hLowInfo) &&
        Objects.equals(this.new1dLowInfo, statRegion.new1dLowInfo) &&
        Objects.equals(this.new1wLowInfo, statRegion.new1wLowInfo) &&
        Objects.equals(this.oldLowInfo, statRegion.oldLowInfo) &&
        Objects.equals(this.suppressedHighInfo, statRegion.suppressedHighInfo) &&
        Objects.equals(this.suppressedMediumInfo, statRegion.suppressedMediumInfo) &&
        Objects.equals(this.suppressedLowInfo, statRegion.suppressedLowInfo) &&
        Objects.equals(this.region, statRegion.region) &&
        Objects.equals(this.regionId, statRegion.regionId) &&
        Objects.equals(this.stat, statRegion.stat) &&
        Objects.equals(this.statId, statRegion.statId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, new1hHighPass, new1dHighPass, new1wHighPass, oldHighPass, new1hHighFail, new1dHighFail, new1wHighFail, oldHighFail, new1hHighWarn, new1dHighWarn, new1wHighWarn, oldHighWarn, new1hHighError, new1dHighError, new1wHighError, oldHighError, new1hMediumPass, new1dMediumPass, new1wMediumPass, oldMediumPass, new1hMediumFail, new1dMediumFail, new1wMediumFail, oldMediumFail, new1hMediumWarn, new1dMediumWarn, new1wMediumWarn, oldMediumWarn, new1hMediumError, new1dMediumError, new1wMediumError, oldMediumError, new1hLowPass, new1dLowPass, new1wLowPass, oldLowPass, new1hLowFail, new1dLowFail, new1wLowFail, oldLowFail, new1hLowWarn, new1dLowWarn, new1wLowWarn, oldLowWarn, new1hLowError, new1dLowError, new1wLowError, oldLowError, suppressedHighPass, suppressedHighFail, suppressedHighWarn, suppressedHighError, suppressedMediumPass, suppressedMediumFail, suppressedMediumWarn, suppressedMediumError, suppressedLowPass, suppressedLowFail, suppressedLowWarn, suppressedLowError, new1hHighInfo, new1dHighInfo, new1wHighInfo, oldHighInfo, new1hMediumInfo, new1dMediumInfo, new1wMediumInfo, oldMediumInfo, new1hLowInfo, new1dLowInfo, new1wLowInfo, oldLowInfo, suppressedHighInfo, suppressedMediumInfo, suppressedLowInfo, region, regionId, stat, statId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatRegion {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    new1hHighPass: ").append(toIndentedString(new1hHighPass)).append("\n");
    sb.append("    new1dHighPass: ").append(toIndentedString(new1dHighPass)).append("\n");
    sb.append("    new1wHighPass: ").append(toIndentedString(new1wHighPass)).append("\n");
    sb.append("    oldHighPass: ").append(toIndentedString(oldHighPass)).append("\n");
    sb.append("    new1hHighFail: ").append(toIndentedString(new1hHighFail)).append("\n");
    sb.append("    new1dHighFail: ").append(toIndentedString(new1dHighFail)).append("\n");
    sb.append("    new1wHighFail: ").append(toIndentedString(new1wHighFail)).append("\n");
    sb.append("    oldHighFail: ").append(toIndentedString(oldHighFail)).append("\n");
    sb.append("    new1hHighWarn: ").append(toIndentedString(new1hHighWarn)).append("\n");
    sb.append("    new1dHighWarn: ").append(toIndentedString(new1dHighWarn)).append("\n");
    sb.append("    new1wHighWarn: ").append(toIndentedString(new1wHighWarn)).append("\n");
    sb.append("    oldHighWarn: ").append(toIndentedString(oldHighWarn)).append("\n");
    sb.append("    new1hHighError: ").append(toIndentedString(new1hHighError)).append("\n");
    sb.append("    new1dHighError: ").append(toIndentedString(new1dHighError)).append("\n");
    sb.append("    new1wHighError: ").append(toIndentedString(new1wHighError)).append("\n");
    sb.append("    oldHighError: ").append(toIndentedString(oldHighError)).append("\n");
    sb.append("    new1hMediumPass: ").append(toIndentedString(new1hMediumPass)).append("\n");
    sb.append("    new1dMediumPass: ").append(toIndentedString(new1dMediumPass)).append("\n");
    sb.append("    new1wMediumPass: ").append(toIndentedString(new1wMediumPass)).append("\n");
    sb.append("    oldMediumPass: ").append(toIndentedString(oldMediumPass)).append("\n");
    sb.append("    new1hMediumFail: ").append(toIndentedString(new1hMediumFail)).append("\n");
    sb.append("    new1dMediumFail: ").append(toIndentedString(new1dMediumFail)).append("\n");
    sb.append("    new1wMediumFail: ").append(toIndentedString(new1wMediumFail)).append("\n");
    sb.append("    oldMediumFail: ").append(toIndentedString(oldMediumFail)).append("\n");
    sb.append("    new1hMediumWarn: ").append(toIndentedString(new1hMediumWarn)).append("\n");
    sb.append("    new1dMediumWarn: ").append(toIndentedString(new1dMediumWarn)).append("\n");
    sb.append("    new1wMediumWarn: ").append(toIndentedString(new1wMediumWarn)).append("\n");
    sb.append("    oldMediumWarn: ").append(toIndentedString(oldMediumWarn)).append("\n");
    sb.append("    new1hMediumError: ").append(toIndentedString(new1hMediumError)).append("\n");
    sb.append("    new1dMediumError: ").append(toIndentedString(new1dMediumError)).append("\n");
    sb.append("    new1wMediumError: ").append(toIndentedString(new1wMediumError)).append("\n");
    sb.append("    oldMediumError: ").append(toIndentedString(oldMediumError)).append("\n");
    sb.append("    new1hLowPass: ").append(toIndentedString(new1hLowPass)).append("\n");
    sb.append("    new1dLowPass: ").append(toIndentedString(new1dLowPass)).append("\n");
    sb.append("    new1wLowPass: ").append(toIndentedString(new1wLowPass)).append("\n");
    sb.append("    oldLowPass: ").append(toIndentedString(oldLowPass)).append("\n");
    sb.append("    new1hLowFail: ").append(toIndentedString(new1hLowFail)).append("\n");
    sb.append("    new1dLowFail: ").append(toIndentedString(new1dLowFail)).append("\n");
    sb.append("    new1wLowFail: ").append(toIndentedString(new1wLowFail)).append("\n");
    sb.append("    oldLowFail: ").append(toIndentedString(oldLowFail)).append("\n");
    sb.append("    new1hLowWarn: ").append(toIndentedString(new1hLowWarn)).append("\n");
    sb.append("    new1dLowWarn: ").append(toIndentedString(new1dLowWarn)).append("\n");
    sb.append("    new1wLowWarn: ").append(toIndentedString(new1wLowWarn)).append("\n");
    sb.append("    oldLowWarn: ").append(toIndentedString(oldLowWarn)).append("\n");
    sb.append("    new1hLowError: ").append(toIndentedString(new1hLowError)).append("\n");
    sb.append("    new1dLowError: ").append(toIndentedString(new1dLowError)).append("\n");
    sb.append("    new1wLowError: ").append(toIndentedString(new1wLowError)).append("\n");
    sb.append("    oldLowError: ").append(toIndentedString(oldLowError)).append("\n");
    sb.append("    suppressedHighPass: ").append(toIndentedString(suppressedHighPass)).append("\n");
    sb.append("    suppressedHighFail: ").append(toIndentedString(suppressedHighFail)).append("\n");
    sb.append("    suppressedHighWarn: ").append(toIndentedString(suppressedHighWarn)).append("\n");
    sb.append("    suppressedHighError: ").append(toIndentedString(suppressedHighError)).append("\n");
    sb.append("    suppressedMediumPass: ").append(toIndentedString(suppressedMediumPass)).append("\n");
    sb.append("    suppressedMediumFail: ").append(toIndentedString(suppressedMediumFail)).append("\n");
    sb.append("    suppressedMediumWarn: ").append(toIndentedString(suppressedMediumWarn)).append("\n");
    sb.append("    suppressedMediumError: ").append(toIndentedString(suppressedMediumError)).append("\n");
    sb.append("    suppressedLowPass: ").append(toIndentedString(suppressedLowPass)).append("\n");
    sb.append("    suppressedLowFail: ").append(toIndentedString(suppressedLowFail)).append("\n");
    sb.append("    suppressedLowWarn: ").append(toIndentedString(suppressedLowWarn)).append("\n");
    sb.append("    suppressedLowError: ").append(toIndentedString(suppressedLowError)).append("\n");
    sb.append("    new1hHighInfo: ").append(toIndentedString(new1hHighInfo)).append("\n");
    sb.append("    new1dHighInfo: ").append(toIndentedString(new1dHighInfo)).append("\n");
    sb.append("    new1wHighInfo: ").append(toIndentedString(new1wHighInfo)).append("\n");
    sb.append("    oldHighInfo: ").append(toIndentedString(oldHighInfo)).append("\n");
    sb.append("    new1hMediumInfo: ").append(toIndentedString(new1hMediumInfo)).append("\n");
    sb.append("    new1dMediumInfo: ").append(toIndentedString(new1dMediumInfo)).append("\n");
    sb.append("    new1wMediumInfo: ").append(toIndentedString(new1wMediumInfo)).append("\n");
    sb.append("    oldMediumInfo: ").append(toIndentedString(oldMediumInfo)).append("\n");
    sb.append("    new1hLowInfo: ").append(toIndentedString(new1hLowInfo)).append("\n");
    sb.append("    new1dLowInfo: ").append(toIndentedString(new1dLowInfo)).append("\n");
    sb.append("    new1wLowInfo: ").append(toIndentedString(new1wLowInfo)).append("\n");
    sb.append("    oldLowInfo: ").append(toIndentedString(oldLowInfo)).append("\n");
    sb.append("    suppressedHighInfo: ").append(toIndentedString(suppressedHighInfo)).append("\n");
    sb.append("    suppressedMediumInfo: ").append(toIndentedString(suppressedMediumInfo)).append("\n");
    sb.append("    suppressedLowInfo: ").append(toIndentedString(suppressedLowInfo)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("    statId: ").append(toIndentedString(statId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

