/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.CustomSignature;
import io.evident.models.ExternalAccount;
import io.evident.models.Organization;
import io.evident.models.SubOrganization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) Team object
 */
@ApiModel(description = "A(n) Team object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class Team {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("custom_signatures")
  private List<CustomSignature> customSignatures = new ArrayList<CustomSignature>();

  @SerializedName("custom_signature_ids")
  private List<Integer> customSignatureIds = new ArrayList<Integer>();

  @SerializedName("external_accounts")
  private List<ExternalAccount> externalAccounts = new ArrayList<ExternalAccount>();

  @SerializedName("external_account_ids")
  private List<Integer> externalAccountIds = new ArrayList<Integer>();

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("organization_id")
  private Integer organizationId = null;

  @SerializedName("sub_organization")
  private SubOrganization subOrganization = null;

  @SerializedName("sub_organization_id")
  private Integer subOrganizationId = null;

  public Team id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Team name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the team
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of the team")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Team createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Team updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Team customSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
    return this;
  }

  public Team addCustomSignaturesItem(CustomSignature customSignaturesItem) {
    this.customSignatures.add(customSignaturesItem);
    return this;
  }

   /**
   * Associated Custom Signatures
   * @return customSignatures
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures")
  public List<CustomSignature> getCustomSignatures() {
    return customSignatures;
  }

  public void setCustomSignatures(List<CustomSignature> customSignatures) {
    this.customSignatures = customSignatures;
  }

  public Team customSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
    return this;
  }

  public Team addCustomSignatureIdsItem(Integer customSignatureIdsItem) {
    this.customSignatureIds.add(customSignatureIdsItem);
    return this;
  }

   /**
   * Associated Custom Signatures IDs
   * @return customSignatureIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Custom Signatures IDs")
  public List<Integer> getCustomSignatureIds() {
    return customSignatureIds;
  }

  public void setCustomSignatureIds(List<Integer> customSignatureIds) {
    this.customSignatureIds = customSignatureIds;
  }

  public Team externalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
    return this;
  }

  public Team addExternalAccountsItem(ExternalAccount externalAccountsItem) {
    this.externalAccounts.add(externalAccountsItem);
    return this;
  }

   /**
   * Associated External Accounts
   * @return externalAccounts
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts")
  public List<ExternalAccount> getExternalAccounts() {
    return externalAccounts;
  }

  public void setExternalAccounts(List<ExternalAccount> externalAccounts) {
    this.externalAccounts = externalAccounts;
  }

  public Team externalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
    return this;
  }

  public Team addExternalAccountIdsItem(Integer externalAccountIdsItem) {
    this.externalAccountIds.add(externalAccountIdsItem);
    return this;
  }

   /**
   * Associated External Accounts IDs
   * @return externalAccountIds
  **/
  @ApiModelProperty(example = "null", value = "Associated External Accounts IDs")
  public List<Integer> getExternalAccountIds() {
    return externalAccountIds;
  }

  public void setExternalAccountIds(List<Integer> externalAccountIds) {
    this.externalAccountIds = externalAccountIds;
  }

  public Team organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Associated Organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public Team organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Associated Organization ID
   * @return organizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public Team subOrganization(SubOrganization subOrganization) {
    this.subOrganization = subOrganization;
    return this;
  }

   /**
   * Associated Sub Organization
   * @return subOrganization
  **/
  @ApiModelProperty(example = "null", value = "Associated Sub Organization")
  public SubOrganization getSubOrganization() {
    return subOrganization;
  }

  public void setSubOrganization(SubOrganization subOrganization) {
    this.subOrganization = subOrganization;
  }

  public Team subOrganizationId(Integer subOrganizationId) {
    this.subOrganizationId = subOrganizationId;
    return this;
  }

   /**
   * Associated Sub Organization ID
   * @return subOrganizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Sub Organization ID")
  public Integer getSubOrganizationId() {
    return subOrganizationId;
  }

  public void setSubOrganizationId(Integer subOrganizationId) {
    this.subOrganizationId = subOrganizationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.id, team.id) &&
        Objects.equals(this.name, team.name) &&
        Objects.equals(this.createdAt, team.createdAt) &&
        Objects.equals(this.updatedAt, team.updatedAt) &&
        Objects.equals(this.customSignatures, team.customSignatures) &&
        Objects.equals(this.customSignatureIds, team.customSignatureIds) &&
        Objects.equals(this.externalAccounts, team.externalAccounts) &&
        Objects.equals(this.externalAccountIds, team.externalAccountIds) &&
        Objects.equals(this.organization, team.organization) &&
        Objects.equals(this.organizationId, team.organizationId) &&
        Objects.equals(this.subOrganization, team.subOrganization) &&
        Objects.equals(this.subOrganizationId, team.subOrganizationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, createdAt, updatedAt, customSignatures, customSignatureIds, externalAccounts, externalAccountIds, organization, organizationId, subOrganization, subOrganizationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Team {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    customSignatures: ").append(toIndentedString(customSignatures)).append("\n");
    sb.append("    customSignatureIds: ").append(toIndentedString(customSignatureIds)).append("\n");
    sb.append("    externalAccounts: ").append(toIndentedString(externalAccounts)).append("\n");
    sb.append("    externalAccountIds: ").append(toIndentedString(externalAccountIds)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    subOrganization: ").append(toIndentedString(subOrganization)).append("\n");
    sb.append("    subOrganizationId: ").append(toIndentedString(subOrganizationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

