/*
 * ESP Documentation
 * The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.
 *
 * OpenAPI spec version: v2_sdk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.evident.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.evident.models.Organization;
import io.evident.models.Role;
import io.evident.models.SubOrganization;
import io.evident.models.Team;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * A(n) User object
 */
@ApiModel(description = "A(n) User object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:00:39.690-05:00")
public class User {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("time_zone")
  private String timeZone = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("mfa_enabled")
  private Boolean mfaEnabled = null;

  @SerializedName("disable_daily_emails")
  private Boolean disableDailyEmails = null;

  @SerializedName("locked")
  private Boolean locked = null;

  @SerializedName("locked_at")
  private DateTime lockedAt = null;

  @SerializedName("access_level")
  private String accessLevel = null;

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("organization_id")
  private Integer organizationId = null;

  @SerializedName("sub_organizations")
  private List<SubOrganization> subOrganizations = new ArrayList<SubOrganization>();

  @SerializedName("sub_organization_ids")
  private List<Integer> subOrganizationIds = new ArrayList<Integer>();

  @SerializedName("teams")
  private List<Team> teams = new ArrayList<Team>();

  @SerializedName("team_ids")
  private List<Integer> teamIds = new ArrayList<Integer>();

  @SerializedName("role")
  private Role role = null;

  @SerializedName("role_id")
  private Integer roleId = null;

  public User id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public User createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public User email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email of the user
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "The email of the user")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public User timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * The time zone of the user. See Time Zones for a list of valid time zones
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "The time zone of the user. See Time Zones for a list of valid time zones")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public User updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 timestamp when the resource was updated
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "ISO 8601 timestamp when the resource was updated")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public User firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the user
   * @return firstName
  **/
  @ApiModelProperty(example = "null", value = "The first name of the user")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public User lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the user
   * @return lastName
  **/
  @ApiModelProperty(example = "null", value = "The last name of the user")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public User phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * The phone number of the user
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "The phone number of the user")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public User mfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
    return this;
  }

   /**
   * Specifies whether Multi Factor Authentication is enabled or not
   * @return mfaEnabled
  **/
  @ApiModelProperty(example = "null", value = "Specifies whether Multi Factor Authentication is enabled or not")
  public Boolean getMfaEnabled() {
    return mfaEnabled;
  }

  public void setMfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
  }

  public User disableDailyEmails(Boolean disableDailyEmails) {
    this.disableDailyEmails = disableDailyEmails;
    return this;
  }

   /**
   * Specifies whether the daily emails should be turned off or not
   * @return disableDailyEmails
  **/
  @ApiModelProperty(example = "null", value = "Specifies whether the daily emails should be turned off or not")
  public Boolean getDisableDailyEmails() {
    return disableDailyEmails;
  }

  public void setDisableDailyEmails(Boolean disableDailyEmails) {
    this.disableDailyEmails = disableDailyEmails;
  }

  public User locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Specifies whether the user account is locked from accessing ESP
   * @return locked
  **/
  @ApiModelProperty(example = "null", value = "Specifies whether the user account is locked from accessing ESP")
  public Boolean getLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }

  public User lockedAt(DateTime lockedAt) {
    this.lockedAt = lockedAt;
    return this;
  }

   /**
   * The time the user account was locked
   * @return lockedAt
  **/
  @ApiModelProperty(example = "null", value = "The time the user account was locked")
  public DateTime getLockedAt() {
    return lockedAt;
  }

  public void setLockedAt(DateTime lockedAt) {
    this.lockedAt = lockedAt;
  }

  public User accessLevel(String accessLevel) {
    this.accessLevel = accessLevel;
    return this;
  }

   /**
   * The level of access this user has. Team access has access to items belonging only to that team. Sub Organization access has access to items belonging only to all teams under that sub organization. Organization access has access to all sub organizations and teams under that organization. Valid values are organization, sub_organization, team
   * @return accessLevel
  **/
  @ApiModelProperty(example = "null", value = "The level of access this user has. Team access has access to items belonging only to that team. Sub Organization access has access to items belonging only to all teams under that sub organization. Organization access has access to all sub organizations and teams under that organization. Valid values are organization, sub_organization, team")
  public String getAccessLevel() {
    return accessLevel;
  }

  public void setAccessLevel(String accessLevel) {
    this.accessLevel = accessLevel;
  }

  public User organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Associated Organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public User organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Associated Organization ID
   * @return organizationId
  **/
  @ApiModelProperty(example = "null", value = "Associated Organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public User subOrganizations(List<SubOrganization> subOrganizations) {
    this.subOrganizations = subOrganizations;
    return this;
  }

  public User addSubOrganizationsItem(SubOrganization subOrganizationsItem) {
    this.subOrganizations.add(subOrganizationsItem);
    return this;
  }

   /**
   * Associated Sub Organizations
   * @return subOrganizations
  **/
  @ApiModelProperty(example = "null", value = "Associated Sub Organizations")
  public List<SubOrganization> getSubOrganizations() {
    return subOrganizations;
  }

  public void setSubOrganizations(List<SubOrganization> subOrganizations) {
    this.subOrganizations = subOrganizations;
  }

  public User subOrganizationIds(List<Integer> subOrganizationIds) {
    this.subOrganizationIds = subOrganizationIds;
    return this;
  }

  public User addSubOrganizationIdsItem(Integer subOrganizationIdsItem) {
    this.subOrganizationIds.add(subOrganizationIdsItem);
    return this;
  }

   /**
   * Associated Sub Organizations IDs
   * @return subOrganizationIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Sub Organizations IDs")
  public List<Integer> getSubOrganizationIds() {
    return subOrganizationIds;
  }

  public void setSubOrganizationIds(List<Integer> subOrganizationIds) {
    this.subOrganizationIds = subOrganizationIds;
  }

  public User teams(List<Team> teams) {
    this.teams = teams;
    return this;
  }

  public User addTeamsItem(Team teamsItem) {
    this.teams.add(teamsItem);
    return this;
  }

   /**
   * Associated Teams
   * @return teams
  **/
  @ApiModelProperty(example = "null", value = "Associated Teams")
  public List<Team> getTeams() {
    return teams;
  }

  public void setTeams(List<Team> teams) {
    this.teams = teams;
  }

  public User teamIds(List<Integer> teamIds) {
    this.teamIds = teamIds;
    return this;
  }

  public User addTeamIdsItem(Integer teamIdsItem) {
    this.teamIds.add(teamIdsItem);
    return this;
  }

   /**
   * Associated Teams IDs
   * @return teamIds
  **/
  @ApiModelProperty(example = "null", value = "Associated Teams IDs")
  public List<Integer> getTeamIds() {
    return teamIds;
  }

  public void setTeamIds(List<Integer> teamIds) {
    this.teamIds = teamIds;
  }

  public User role(Role role) {
    this.role = role;
    return this;
  }

   /**
   * Associated Role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "Associated Role")
  public Role getRole() {
    return role;
  }

  public void setRole(Role role) {
    this.role = role;
  }

  public User roleId(Integer roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * Associated Role ID
   * @return roleId
  **/
  @ApiModelProperty(example = "null", value = "Associated Role ID")
  public Integer getRoleId() {
    return roleId;
  }

  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.createdAt, user.createdAt) &&
        Objects.equals(this.email, user.email) &&
        Objects.equals(this.timeZone, user.timeZone) &&
        Objects.equals(this.updatedAt, user.updatedAt) &&
        Objects.equals(this.firstName, user.firstName) &&
        Objects.equals(this.lastName, user.lastName) &&
        Objects.equals(this.phone, user.phone) &&
        Objects.equals(this.mfaEnabled, user.mfaEnabled) &&
        Objects.equals(this.disableDailyEmails, user.disableDailyEmails) &&
        Objects.equals(this.locked, user.locked) &&
        Objects.equals(this.lockedAt, user.lockedAt) &&
        Objects.equals(this.accessLevel, user.accessLevel) &&
        Objects.equals(this.organization, user.organization) &&
        Objects.equals(this.organizationId, user.organizationId) &&
        Objects.equals(this.subOrganizations, user.subOrganizations) &&
        Objects.equals(this.subOrganizationIds, user.subOrganizationIds) &&
        Objects.equals(this.teams, user.teams) &&
        Objects.equals(this.teamIds, user.teamIds) &&
        Objects.equals(this.role, user.role) &&
        Objects.equals(this.roleId, user.roleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, email, timeZone, updatedAt, firstName, lastName, phone, mfaEnabled, disableDailyEmails, locked, lockedAt, accessLevel, organization, organizationId, subOrganizations, subOrganizationIds, teams, teamIds, role, roleId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mfaEnabled: ").append(toIndentedString(mfaEnabled)).append("\n");
    sb.append("    disableDailyEmails: ").append(toIndentedString(disableDailyEmails)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    lockedAt: ").append(toIndentedString(lockedAt)).append("\n");
    sb.append("    accessLevel: ").append(toIndentedString(accessLevel)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    subOrganizations: ").append(toIndentedString(subOrganizations)).append("\n");
    sb.append("    subOrganizationIds: ").append(toIndentedString(subOrganizationIds)).append("\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    teamIds: ").append(toIndentedString(teamIds)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

